// Leah-PP service worker: network first (always newest when online), cache as backup when offline.
const CACHE='lantern-v39';
const FILES=['./','index.html','manifest.json','questions-index.json','q-math-6.json','q-math-7.json','q-math-8.json','q-english-6.json','q-english-7.json','q-english-8.json','q-thai-6.json','q-thai-7.json','q-thai-8.json','q-chinese-6.json','q-chinese-7.json','q-chinese-8.json','q-general-6.json','q-general-7.json','q-general-8.json','leah-walk.png','leah-idle.png','dad-idle.png','mom-idle.png','peb-idle.png','nuan-idle.png','cave-floor.jpg','cave-wall.jpg','tiles-cave.png','tiles-village.png','tiles-hedge.png','obj-fountain.png','props-village.png','props-cave.png','props-dungeon.png','buildings-village.png','tiles-house.png','furniture.png','play.html','kid-curly2-idle.png','kid-curly2-stand.png','kid-curly2-walk.png','play.webmanifest','firebase-config.js','tiles-cliff.png','tiles-water.png','tiles-cobble.png','props-mountain.png','props-farm.png','obj-lightstone.png','obj-lightstone-plaza.png','obj-cave-crystal.png','obj-rockfall.png','obj-bridge-rope.png','obj-bridge-stone.png','obj-pier.png','obj-fountain-big.png','obj-fountain-old.png','map-plaza.jpg','capital-greybox.png','bld-academy.png','bld-lanna-house.png','bld-lanna-house2.png','bld-market-stall.png','obj-lantern-shrine.png','obj-bridge-arch.png','obj-stairs-stone.png','obj-pier-teak.png','tiles-forest.png','tiles-desert.png','tiles-ulake.png','tiles-sky.png','kid-braids-idle.png','kid-braids-stand.png','kid-braids-walk.png','kid-ponytail-idle.png','kid-ponytail-stand.png','kid-ponytail-walk.png','kid-bob-idle.png','kid-bob-stand.png','kid-bob-walk.png','kid-curly-idle.png','kid-curly-stand.png','kid-curly-walk.png','kid-blond-idle.png','kid-blond-stand.png','kid-blond-walk.png','kid-spiky-idle.png','kid-spiky-stand.png','kid-spiky-walk.png','icon-192.png','icon-512.png','icon-maskable-512.png','apple-touch-icon.png','favicon-32.png','logo.png','title-art.jpg'];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>Promise.all(FILES.map(f=>c.add(f).catch(()=>null)))));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(self.clients.claim());e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  // always ask the server for the newest copy (no-cache revalidates quickly); fall back to the saved copy when offline
  let req;try{req=e.request.mode==='navigate'?new Request(e.request.url,{cache:'no-cache',credentials:'same-origin'}):new Request(e.request,{cache:'no-cache'})}catch(err){req=e.request}
  e.respondWith(fetch(req).then(r=>{const cp=r.clone();caches.open(CACHE).then(c=>c.put(e.request,cp)).catch(()=>{});return r}).catch(()=>caches.match(e.request)));
});
