// test_124_sit.js — รุ่น 1.24: แสงขอบแบบเดียวกันทุกของที่กดได้ · กรอบประตูตรงบานประตู · ลูกศรแดงช้า · ม้านั่ง 2 ที่นั่ง (แตะจอจริง) · PORT=... CHROME_EXE=...
const p=require('puppeteer');
(async()=>{const b=await p.launch({executablePath:process.env.CHROME_EXE||undefined,args:['--no-sandbox']});
const pg=await b.newPage();await pg.setViewport({width:844,height:390,isMobile:true,hasTouch:true,deviceScaleFactor:2});const errs=[];pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.evaluate(()=>localStorage.clear());await pg.reload({waitUntil:'load'});await new Promise(r=>setTimeout(r,6000));
const out={};
out.setup=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));gmMakeSlot();const d=Store.all();S=d.slots[d.cur];startGame();await sleep(1500);document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));
 try{for(let i=0;i<10&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(120)}DLG=null;PAUSE=false}catch(e){}fpsChecks=6;GM.hour=10;goMap('farm');await sleep(1500);try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(150)}}catch(e){}document.querySelectorAll('#hud,#dlg').forEach(e=>e.classList.add('hide'));   // the farm greets a first visit with a talk: close it, or taps are ignored
 const rings=M.objs.filter(o=>o.ring);const ho=M.objs.find(o=>o.farmHouse);
 return{version:VERSION,ringsOfLight:rings.length,allRingPicturesReady:rings.every(o=>!!IMG[o.ring]),breath:[0,.75,1.5,2.25].map(t=>+g9bPulse(t).toFixed(2)),door:{centreOnPath:Math.round(G9.door[0]*T),houseDoorLeafAt:ho?Math.round(ho.x-ho.sw/2+97.5):null,numbers:G9DOOR},benches:(G9B.benches||[]).length,seats:g9bSeats().length}});
const place=async(x,y)=>pg.evaluate(async(x,y)=>{try{closeModal()}catch(e){}try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await new Promise(r=>setTimeout(r,120))}}catch(e){}PAUSE=false;DLG=null;HOLD=null;P.sit=null;let best=null;for(let r=0;r<5&&!best;r++)for(let dy=-r;dy<=r&&!best;dy++)for(let dx=-r;dx<=r&&!best;dx++){const tx=Math.floor(x/T)+dx,ty=Math.floor(y/T)+dy;if(!M.SOLID.has(key(tx,ty)))best=[tx*T+16,ty*T+16]}P.x=best[0];P.y=best[1];P.path=null;P.act=null;await new Promise(r=>setTimeout(r,1500))},x,y);   // never start inside something solid: the player could not walk away
const scr=async(wx,wy)=>pg.evaluate((wx,wy)=>{const cv=document.getElementById('c'),r=cv.getBoundingClientRect(),dpr=devicePixelRatio||1;return [(wx-camX)*SC/dpr+r.left,(wy-camY)*SC/dpr+r.top]},wx,wy);
const bench=await pg.evaluate(()=>G9B.benches[1]);   // the bench right of the campfire
for(const [side,dx] of [['L',-14],['R',14]]){await place(bench[0]+30,bench[1]+120);const c=await scr(bench[0]+dx,bench[1]-14);await pg.touchscreen.tap(c[0],c[1]);await new Promise(r=>setTimeout(r,250));
 const s0=await pg.evaluate(()=>({sat:!!P.sit,talkOpen:!!DLG,paused:PAUSE}));let sat=null;for(let k=0;k<24&&!sat;k++){await new Promise(r=>setTimeout(r,250));sat=await pg.evaluate(()=>P.sit?{side:P.sit.side,x:Math.round(P.x)}:null)}
 out['sit'+side]={rightAfterTap:s0,satAfterWalking:sat,expectedX:Math.round(bench[0]+(side==='L'?-1:1)*bench[2]*.23)};if(side==='R')await pg.screenshot({path:'t_sit.png'})}
// stand up by tapping the ground further away
const g=await scr(bench[0]+10,bench[1]+110);await pg.touchscreen.tap(g[0],g[1]);await new Promise(r=>setTimeout(r,1800));out.standUp=await pg.evaluate(b=>({sitting:!!P.sit,walkedAwayPx:Math.round(Math.hypot(P.x-b[0],P.y-b[1]))}),bench);
await place(bench[0]-10,bench[1]+18);out.button=await pg.evaluate(async()=>{await new Promise(r=>setTimeout(r,1200));const w=document.getElementById('atkL').textContent,n=g9bNear();autoAct();await new Promise(r=>setTimeout(r,700));return{word:w,nearest:n&&n.k,stillSittingAfterPress:!!P.sit,side:P.sit&&P.sit.side,moving:P.moving}});
await pg.evaluate(async()=>{P.sit=null;P.x=G9.door[0]*T+70;P.y=(G9.door[1]+3.2)*T;P.path=null;await new Promise(r=>setTimeout(r,2500))});await pg.screenshot({path:'t_door.png'});
console.log(JSON.stringify(out));console.log('errors',errs.length,errs.slice(0,4));await b.close()})();
