// test_129_layout.js — รุ่น 1.29: ปุ่มกลมเฉพาะจอสัมผัส · บลิ๊งเหนือสกิล · ช่องสกิล 3 ช่อง · สมาธิแทนออโต้ · ลุกจากม้านั่งด้วยจอย · คอมพิวเตอร์ใช้แถบปุ่มเดิม · PORT=... CHROME_EXE=...
const p=require('puppeteer');
const boot=async(pg)=>{await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.evaluate(()=>localStorage.clear());await pg.reload({waitUntil:'load'});await new Promise(r=>setTimeout(r,6000));
 return pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));gmMakeSlot();const d=Store.all();S=d.slots[d.cur];delete S.joy;startGame();await sleep(1500);document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));fpsChecks=6;GM.hour=10;goMap('farm');await sleep(1500);
  try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(150)}DLG=null;PAUSE=false}catch(e){}document.querySelectorAll('#dlg').forEach(e=>e.classList.add('hide'));await sleep(800);
  const B=[...document.getElementById('act').children].map(b=>{const r=b.getBoundingClientRect(),cs=getComputedStyle(b);return{id:b.id,x:Math.round(r.left),y:Math.round(r.top),w:Math.round(r.width),h:Math.round(r.height),round:cs.borderTopLeftRadius==='50%',word:(b.querySelector('small')||b).textContent.trim()}}).filter(q=>q.w>0);
  let ov=[];for(let i=0;i<B.length;i++)for(let j=i+1;j<B.length;j++){const a=B[i],c=B[j];if(a.x<c.x+c.w&&c.x<a.x+a.w&&a.y<c.y+c.h&&c.y<a.y+a.h&&Math.hypot(a.x+a.w/2-c.x-c.w/2,a.y+a.h/2-c.y-c.h/2)<(a.w+c.w)/2-1)ov.push(a.id+'/'+c.id)}
  const mm=document.getElementById('mmw'),mr=mm?mm.getBoundingClientRect():null,j=document.getElementById('joy'),jr=j.getBoundingClientRect();window._jc=[jr.left+56,jr.top+56];
  return{version:VERSION,thumbs:document.body.classList.contains('thumbs'),buttons:B.map(q=>q.id+'('+q.word+') '+q.w+' @'+q.x+','+q.y+(q.round?' round':' square')),overlapping:ov,allOnScreen:B.every(q=>q.x>=0&&q.y>=0&&q.x+q.w<=innerWidth&&q.y+q.h<=innerHeight),underMinimap:mr?B.filter(q=>q.y<mr.bottom&&q.x+q.w>mr.left&&q.y+q.h>mr.top).map(q=>q.id):[],stickShowing:!j.classList.contains('hide')&&jr.width>0}})};
(async()=>{const b=await p.launch({executablePath:process.env.CHROME_EXE||undefined,args:['--no-sandbox']});const out={};const errs=[];
// a phone
let pg=await b.newPage();await pg.setViewport({width:812,height:330,isMobile:true,hasTouch:true,deviceScaleFactor:2.6});pg.on('pageerror',e=>errs.push(e.message));out.phone=await boot(pg);
// sit on a bench by tapping it, then push the stick: the player must stand up and walk
const bench=await pg.evaluate(()=>G9B.benches[1]);await pg.evaluate(async b=>{let best=null;for(let r=0;r<5&&!best;r++)for(let dy=-r;dy<=r&&!best;dy++)for(let dx=-r;dx<=r&&!best;dx++){const tx=Math.floor((b[0]+30)/T)+dx,ty=Math.floor((b[1]+90)/T)+dy;if(!M.SOLID.has(key(tx,ty)))best=[tx*T+16,ty*T+16]}P.x=best[0];P.y=best[1];P.path=null;await new Promise(r=>setTimeout(r,1200))},bench);
const c=await pg.evaluate(b=>{const cv=document.getElementById('c'),r=cv.getBoundingClientRect(),dpr=devicePixelRatio||1;return [((b[0]-14)-camX)*SC/dpr+r.left,((b[1]-14)-camY)*SC/dpr+r.top]},bench);await pg.touchscreen.tap(c[0],c[1]);let sat=false;for(let k=0;k<24&&!sat;k++){await new Promise(r=>setTimeout(r,250));sat=await pg.evaluate(()=>!!P.sit)}
await new Promise(r=>setTimeout(r,600));const jc=await pg.evaluate(()=>window._jc),p0=await pg.evaluate(()=>[P.x,P.y]);await pg.touchscreen.touchStart(jc[0],jc[1]);await pg.touchscreen.touchMove(jc[0],jc[1]+38);await new Promise(r=>setTimeout(r,900));const st=await pg.evaluate(p0=>({stillSitting:!!P.sit,walkedPx:Math.round(Math.hypot(P.x-p0[0],P.y-p0[1]))}),p0);await pg.touchscreen.touchEnd();
out.bench={satByTapping:sat,afterPushingTheStickDown:st};await pg.screenshot({path:'v_phone.png'});await pg.close();
// a computer
pg=await b.newPage();await pg.setViewport({width:1280,height:720,isMobile:false,hasTouch:false,deviceScaleFactor:1});pg.on('pageerror',e=>errs.push(e.message));out.computer=await boot(pg);await pg.screenshot({path:'v_pc.png'});
console.log(JSON.stringify(out));console.log('errors',errs.length,errs.slice(0,4));await b.close()})();
