// 1.57 actual mouse/touch: twelve slots, hands, style identities, cosmetics, transactions and saves.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const out=process.env.OUT_DIR||'/tmp/leah-ui-157';fs.mkdirSync(out,{recursive:true});const errors=[],results={},sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function press(pg,selector,touch){const e=await pg.$(selector);assert(e,'control '+selector);await e.scrollIntoView();const r=await e.boundingBox();assert(r,'visible '+selector);const x=r.x+r.width/2,y=r.y+r.height/2;assert(x>=0&&x<=pg.viewport().width&&y>=0&&y<=pg.viewport().height,'on-screen '+selector);assert(await pg.evaluate(({x,y,selector})=>!!document.elementFromPoint(x,y)?.closest(selector),{x,y,selector}),'uncovered '+selector);if(touch)await pg.touchscreen.tap(x,y);else await pg.mouse.click(x,y);await sleep(110)}
async function boot(browser,w,h,touch,missing=''){const context=await browser.createBrowserContext(),pg=await context.newPage();await pg.setViewport({width:w,height:h,isMobile:touch,hasTouch:touch,deviceScaleFactor:1});await pg.setBypassServiceWorker(true);pg.on('pageerror',e=>errors.push(missing+': '+e.message));
 let release;const gate=new Promise(r=>release=r);if(missing){await pg.setRequestInterception(true);pg.on('request',async r=>{const file=new URL(r.url()).pathname.split('/').pop();if(missing==='late'&&file==='equipment-157.json')await gate;if(missing==='all'&&['equipment-157.json','equipment-157.webp','outfit-157.webp'].includes(file)||missing==='gear'&&file==='equipment-157.webp'||missing==='outfit'&&file==='outfit-157.webp'||missing==='character'&&/kid-spiky-(walk|stand|idle)\.png/.test(file))return r.respond({status:404,body:'missing'});return r.continue()})}
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(m=>!document.getElementById('load')&&typeof UI157!=='undefined'&&(m==='late'||UI157.ready)&&ROOM2,{timeout:30000},missing);
 await pg.evaluate(()=>{gmMakeSlot();const d=Store.all();S=d.slots[d.cur];S.gmInit=1;S.seen={intro:true};S.age=18;S.kid=5;S.lv=12;S.coins=1600;S.snd=true;S.mus=false;save();startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));fpsChecks=6;GM.hour=10;goMap('farm')});await sleep(1200);
 await pg.evaluate(()=>{closeModal();DLG=null;PAUSE=false;HOLD=null;S.inv=[mkItem('sw',0),mkGear('armor',1),mkGear('acc',0)];S.eq=0;S.eqA=1;S.eqC=2;S.equipment157={};S.store=[];S.bagUp=3;S.storeUp=3;S.age=18;S.name='ต้นกล้า';S.lv=12;buildPlayerSheets();gridFix();S.hp=hpMax();save();hud()});return{context,pg,release}}
async function inject(pg,kind,rar=2){return pg.evaluate(({kind,rar})=>{const it=mkEquipment157(kind,rar);S.inv.push(it);gridFix();save();openGridBag();return {u:it.u,i:S.inv.indexOf(it),stored:S.store.some(w=>w.u===it.u)}},{kind,rar})}
async function equip(pg,kind,side,touch,rar=2){const previous=await pg.evaluate(()=>['weapon','offhand'].map(ui157Get).filter(Boolean).map(it=>it.u));const it=await inject(pg,kind,rar);assert(!it.stored,'fixture fits bag '+kind);await press(pg,'.gbIt[data-src="bag"][data-i="'+it.i+'"]',touch);await press(pg,side==='offhand'&&kind!=='shield'||side==='ringRight'?'#equip157-other':'#gbEqB',touch);assert.equal(await pg.evaluate(k=>ui157Get(k)?.u,side),it.u,'actual equip '+kind+' -> '+side);if(!await pg.evaluate(k=>!!ui157Get(k)?.slot,side)){for(const u of previous){const i=await pg.evaluate(u=>S.inv.findIndex((it,i)=>it.u===u&&!isWorn(i)),u);if(i>=0){await press(pg,'.gbIt[data-src="bag"][data-i="'+i+'"]',touch);await press(pg,'#deposit157',touch);assert(await pg.evaluate(u=>S.store.some(w=>w.u===u),u),'real deposit preserves released weapon')}}}return it.u}
async function state(pg){return pg.evaluate(()=>({items:[...S.inv,...S.store].map(it=>it.u).sort(),worn:Object.fromEntries(Object.keys(EQ157).map(k=>[k,ui157Get(k)?.u||null])),names:Object.fromEntries(Object.keys(EQ157).map(k=>[k,ui157Get(k)?itemName(ui157Get(k)):null])),atk:atkPow(),def:defVal(),hp:hpMax(),coins:S.coins}))}
async function shot(pg,name){await pg.$eval('#mBody',e=>e.scrollTop=0);await pg.screenshot({path:path.join(out,name+'.png')})}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE||undefined,args:['--no-sandbox']});try{
 for(const [name,w,h,touch,missing] of [['pc',1366,768,false,''],['phone',812,330,true,''],['small',667,375,true,''],['missing-all',812,375,true,'all'],['missing-gear',812,375,true,'gear'],['missing-outfit',812,375,true,'outfit'],['missing-character',812,375,true,'character'],['late-art',812,375,true,'late']]){if(process.env.CASE157&&process.env.CASE157!==name)continue;const{context,pg,release}=await boot(browser,w,h,touch,missing);try{
  if(missing==='late'){assert.equal(await pg.evaluate(()=>UI157.ready),false);await press(pg,'#bBag',touch);const it=await inject(pg,'ring_blue');await press(pg,'.gbIt[data-src="bag"][data-i="'+it.i+'"]',touch);const selected=await pg.evaluate(()=>({...GB.sel}));release();await pg.waitForFunction(()=>UI157.ready);assert.deepEqual(await pg.evaluate(()=>GB.sel),selected);assert.equal(await pg.$$eval('#equip157-other',bs=>bs.length),1,'late art keeps one left/right control');assert.equal(await pg.$$eval('#deposit157',bs=>bs.length),1,'late art keeps one storage control');await press(pg,'#equip157-other',touch);assert.equal(await pg.evaluate(()=>ui157Get('ringRight').u),it.u);await press(pg,'#mX',touch)}
  const artCount=await pg.evaluate(()=>Object.keys(UI157.art).length);assert.equal(artCount,missing==='all'?0:missing==='gear'?12:missing==='outfit'?24:36,'independent artwork banks');const originals=(await state(pg)).items;
  await press(pg,'#bBag',touch);assert.equal(await pg.$$eval('[data-eqslot]',bs=>bs.length),12);assert(await pg.$$eval('[data-eqslot]',bs=>bs.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44&&b.getAttribute('aria-label')})),'all 12 labeled hit areas');
  await press(pg,'#catalog157',touch);assert.equal(await pg.$$eval('[data-give157]',bs=>bs.length),25);await shot(pg,name+'-catalog');await press(pg,'#full157',touch);const full=await state(pg);assert(originals.every(u=>full.items.includes(u)),'GM kit preserves every old item');assert.equal(Object.values(full.worn).filter(Boolean).length,12);assert.notEqual(full.worn.ringLeft,full.worn.ringRight);assert.equal(await pg.evaluate(()=>ui157Get('offhand').slot),'shield');
  const styleBefore=await pg.$eval('#equipPortrait',c=>c.toDataURL()),shoeBefore=await pg.$eval('[data-eqslot="boots"] canvas',c=>c.toDataURL());if(name==='pc')await shot(pg,'pc-outfit-a');await press(pg,'#style157-b',touch);assert.deepEqual(await state(pg),full,'style changes preserve names, stats, identities, coins and every item');assert.notEqual(await pg.$eval('#equipPortrait',c=>c.toDataURL()),styleBefore,'worn outfit style visibly changes');if(missing!=='all'&&missing!=='outfit')assert.notEqual(await pg.$eval('[data-eqslot="boots"] canvas',c=>c.toDataURL()),shoeBefore,'shoe picture has alternate style');await shot(pg,name+'-outfit-b');
  const mouthStats=await pg.evaluate(()=>({str:gear().str,def:defVal(),hp:hpMax(),atk:atkPow()}));await pg.evaluate(()=>{const it=ui157Get('mouth');it.aff=[{k:'str',v:999}];it.def=999;it.cards=['golem']});assert.deepEqual(await pg.evaluate(()=>({str:gear().str,def:defVal(),hp:hpMax(),atk:atkPow()})),mouthStats,'mouth decoration never grants combat stats');await pg.evaluate(()=>{const it=ui157Get('mouth');it.aff=[];delete it.def;it.cards=[]});
  await press(pg,'[data-eqslot="mouth"]',touch);await press(pg,'#unequip157',touch);assert.equal(await pg.evaluate(()=>ui157Get('mouth')),null);assert.equal((await state(pg)).atk,full.atk,'unequipping cosmetic leaves attack unchanged');await equip(pg,'mouth_rose','mouth',touch);await equip(pg,'ring_blue','ringLeft',touch,0);await equip(pg,'ring_green','ringRight',touch,0);
  const ringWorn=(await state(pg)).worn;await press(pg,'#gbJunk',touch);assert.deepEqual((await state(pg)).worn,ringWorn,'sell ordinary gear protects both worn rings and every slot after index shifts');
  await equip(pg,'sword2','weapon',touch);assert.equal(await pg.evaluate(()=>ui157Get('offhand')),null);assert(await pg.$eval('[data-eqslot="offhand"]',e=>e.classList.contains('locked157')),'two-handed sword locks left slot');
  await equip(pg,'sword1','weapon',touch);await equip(pg,'shield','offhand',touch);assert.equal(await pg.evaluate(()=>ui157Get('weapon').kind157),'sword1');assert.equal(await pg.evaluate(()=>ui157Get('offhand').kind157),'shield');
  const bowLeft=await equip(pg,'bow1','weapon',touch),bowRight=await equip(pg,'bow1','offhand',touch);assert.notEqual(bowLeft,bowRight,'two separate hand crossbows');await equip(pg,'bow2','weapon',touch);assert.equal(await pg.evaluate(()=>ui157Get('offhand')),null,'longbow uses both hands');
  await equip(pg,'staff1','weapon',touch);await equip(pg,'staff1','offhand',touch);assert.equal(await pg.evaluate(()=>ui157Get('offhand').kind157),'staff1');await equip(pg,'staff2','weapon',touch);assert.equal(await pg.evaluate(()=>ui157Get('offhand')),null);
  if(name==='pc'){await equip(pg,'dagger1','weapon',false);await equip(pg,'dagger1','offhand',false);for(const kind of ['dagger2','axe1','axe2','hammer1','hammer2'])await equip(pg,kind,'weapon',false)}
  
  let saved=await state(pg);await press(pg,'#gbSort',touch);assert.deepEqual(await state(pg),saved,'real sort preserves twelve slot identities and all items');await press(pg,'#gbStore',touch);const stored=await pg.evaluate(()=>S.store[0]?{u:S.store[0].u,i:0}:null);if(stored){await press(pg,'.gbIt[data-src="store"][data-i="'+stored.i+'"]',touch);await press(pg,'#withdraw157',touch);assert(await pg.evaluate(u=>S.inv.some(it=>it.u===u),stored.u),'real withdraw restores the same item');assert.deepEqual(await state(pg),saved,'withdraw preserves equipment and combined item identities')}await press(pg,'#gbStore',touch);assert.deepEqual(await state(pg),saved,'storage toggles preserve equipment');
  if(name==='pc'){const beforeGrant=await state(pg);await press(pg,'#mX',false);await press(pg,'#gmBtn',false);await press(pg,'[data-gm="grant"]',false);assert.deepEqual((await state(pg)).worn,beforeGrant.worn,'receiving GM loot again keeps all worn identities');assert.equal(await pg.evaluate(()=>S.hp),await pg.evaluate(()=>hpMax()),'GM heal uses restored equipment stats');await press(pg,'#mX',false);await press(pg,'#bBag',false)}saved=await state(pg);await shot(pg,name+'-equipment');await pg.reload({waitUntil:'load'});await pg.waitForFunction(()=>!document.getElementById('load')&&UI157.ready);const persisted=await pg.evaluate(()=>{const d=Store.all(),s=d.slots[d.cur];return {items:[...s.inv,...s.store].map(it=>it.u).sort(),extra:s.equipment157,style:s.outfit157}});assert.deepEqual(persisted.items,saved.items,'save/reload keeps every item');assert.equal(persisted.style,'b');for(const [k,d]of Object.entries(await pg.evaluate(()=>EQ157)))if(!d.field)assert.equal(persisted.extra[k],saved.worn[k],'persisted slot '+k);
  results[name]={size:[w,h],art:artCount,slots:12,oldItemsKept:true,sameItemsTwoStyles:true,cosmeticsZeroStats:true,shieldSword:true,dualCrossbows:true,longbow:true,dualWands:true,longStaff:true,otherWeapons:name==='pc',sellProtectsRings:true,sort:true,store:true,reload:true};
 }catch(e){console.error(name,e.message);errors.push(name+': '+e.message);await pg.screenshot({path:path.join(out,name+'-failure.png')})}finally{await context.close()}}
 const{context,pg}=await boot(browser,1366,768,false);try{
  await pg.evaluate(()=>{S.bagUp=0;S.inv=[mkEquipment157('sword1'),mkEquipment157('shield'),mkEquipment157('sword2')];S.eq=0;S.eqA=S.eqC=-1;S.equipment157={offhand:S.inv[1].u};S.store=[];const n=bagRows()*10-8;for(let i=0;i<n;i++)S.inv.push(mkGear('acc',0));gridFix();save()});await press(pg,'#bBag',false);const before=await state(pg),positions=await pg.evaluate(()=>S.inv.map(it=>[it.u,it.gx,it.gy]));await press(pg,'.gbIt[data-src="bag"][data-i="2"]',false);await press(pg,'#gbEqB',false);assert.deepEqual(await state(pg),before,'full bag: replacing two hands rolls back every item and slot');assert.deepEqual(await pg.evaluate(()=>S.inv.map(it=>[it.u,it.gx,it.gy])),positions,'rollback restores exact grid positions');results.fullBagRollback=true;
 }catch(e){errors.push('full bag: '+e.message);await pg.screenshot({path:path.join(out,'full-failure.png')})}finally{await context.close()}
 }finally{await browser.close()}console.log(JSON.stringify(results));console.log('errors',errors.length,errors);if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
