// test_128_thumbs.js — รุ่น 1.28: บังคับแบบ RoV · จอยซ้าย · ปุ่มกลมขวา · ปุ่มนั่งพัก · PORT=... CHROME_EXE=...
const p=require('/home/claude/.npm-global/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer');
(async()=>{const b=await p.launch({executablePath:process.env.CHROME_EXE||'/home/claude/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome',args:['--no-sandbox']});
const pg=await b.newPage();await pg.setViewport({width:812,height:330,isMobile:true,hasTouch:true,deviceScaleFactor:2.6});const errs=[];pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.evaluate(()=>localStorage.clear());await pg.reload({waitUntil:'load'});await new Promise(r=>setTimeout(r,6000));
const R=await pg.evaluate(async()=>{const o={version:VERSION,screen:[innerWidth,innerHeight]};const sleep=ms=>new Promise(r=>setTimeout(r,ms));gmMakeSlot();const d=Store.all();S=d.slots[d.cur];delete S.joy;startGame();await sleep(1500);document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));fpsChecks=6;GM.hour=10;goMap('farm');await sleep(1500);
 try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(150)}DLG=null;PAUSE=false}catch(e){}document.querySelectorAll('#dlg').forEach(e=>e.classList.add('hide'));await sleep(700);
 const vis=[...document.getElementById('act').children].filter(b=>!b.classList.contains('hide')&&b.offsetParent!==null||getComputedStyle(b).position==='fixed'&&!b.classList.contains('hide'));
 const rc=b=>{const r=b.getBoundingClientRect();return{id:b.id,x:Math.round(r.left),y:Math.round(r.top),w:Math.round(r.width),h:Math.round(r.height),round:getComputedStyle(b).borderTopLeftRadius}};
 const B=vis.map(rc).filter(q=>q.w>0);o.buttons=B.map(q=>q.id+' '+q.w+'x'+q.h+' @'+q.x+','+q.y);o.allRound=B.every(q=>q.round==='50%');o.allOnScreen=B.every(q=>q.x>=0&&q.y>=0&&q.x+q.w<=innerWidth&&q.y+q.h<=innerHeight);o.smallestPx=Math.min(...B.map(q=>Math.min(q.w,q.h)));
 let ov=[];for(let i=0;i<B.length;i++)for(let j=i+1;j<B.length;j++){const a=B[i],c=B[j],d=Math.hypot(a.x+a.w/2-c.x-c.w/2,a.y+a.h/2-c.y-c.h/2);if(d<(a.w+c.w)/2-1)ov.push(a.id+'/'+c.id)}o.overlapping=ov;
 const mm=document.getElementById('mmw');if(mm){const r=mm.getBoundingClientRect();o.minimap=[Math.round(r.left),Math.round(r.top),Math.round(r.width),Math.round(r.height)];o.buttonsUnderMinimap=B.filter(q=>q.y<r.bottom&&q.x+q.w>r.left).map(q=>q.id)}
 const j=document.getElementById('joy'),jr=j.getBoundingClientRect();o.stick={onByItselfOnTouch:S.joy===true,showing:!j.classList.contains('hide'),at:[Math.round(jr.left),Math.round(jr.top),Math.round(jr.width)]};
 window._jc=[jr.left+56,jr.top+56];P.x=G9.spawn[0]*T-200;P.y=G9.spawn[1]*T;P.path=null;await sleep(300);window._x0=P.x;return o});
const tapEl=async id=>{const c=await pg.evaluate(id=>{const r=document.getElementById(id).getBoundingClientRect();const e=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return [r.left+r.width/2,r.top+r.height/2,e?(e.closest('button')||e).id||e.tagName:'nothing',[Math.round(r.left),Math.round(r.top),Math.round(r.width),Math.round(r.height)],[innerWidth,innerHeight],document.getElementById('act').className]},id);if(c[2]!==id)console.log('NOTE: at the middle of',id,'the finger meets',c[2],'rect',c[3],'screen',c[4],'act class',c[5]);await pg.touchscreen.tap(c[0],c[1])};
const jc=await pg.evaluate(()=>window._jc);const T2=pg.touchscreen;   // a real finger on the stick
await T2.touchStart(jc[0],jc[1]);await T2.touchMove(jc[0]+38,jc[1]);await new Promise(r=>setTimeout(r,1000));const x1=await pg.evaluate(()=>P.x);await T2.touchEnd();await new Promise(r=>setTimeout(r,300));
Object.assign(R.stick,await pg.evaluate(x1=>({walkedRightPx:Math.round(x1-window._x0),stopsWhenReleased:Math.abs(P.x-x1)<12}),x1));
await tapEl('bRest');await new Promise(r=>setTimeout(r,500));R.rest=await pg.evaluate(()=>({sitsOnPress:!!P.sit,word:document.getElementById('restL').textContent}));
await T2.touchStart(jc[0],jc[1]);await T2.touchMove(jc[0]-38,jc[1]);await new Promise(r=>setTimeout(r,700));await T2.touchEnd();R.rest.standsWhenWalking=await pg.evaluate(()=>!P.sit);
await tapEl('bRest');await new Promise(r=>setTimeout(r,400));const s1=await pg.evaluate(()=>!!P.sit);await tapEl('bRest');await new Promise(r=>setTimeout(r,300));R.rest.pressAgainStands=s1&&await pg.evaluate(()=>!P.sit);
R.actionButtonByCrate=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms)); P.x=M.crate.x;P.y=M.crate.y+26;P.path=null;await sleep(900);const sp=document.querySelector('#bAtk .ctxIc');return{word:document.getElementById('atkL').textContent,icon:sp?sp.dataset.icon||null:null}});
await pg.screenshot({path:'u_thumbs.png'});console.log(JSON.stringify(R));console.log('errors',errs.length,errs.slice(0,4));await b.close()})();
