// 1.55 Quiet Gold: real mouse/touch navigation, reparented settings, shop prices and reachable controls.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const out=process.env.OUT_DIR||'/tmp/leah-ui-155';fs.mkdirSync(out,{recursive:true});const results={},errors=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function press(pg,selector,touch){const el=await pg.$(selector);assert(el,'control '+selector);await el.scrollIntoView();const r=await el.boundingBox();assert(r,'visible '+selector);
 const x=r.x+r.width/2,y=r.y+r.height/2;assert(x>=0&&x<=pg.viewport().width&&y>=0&&y<=pg.viewport().height,'on-screen '+selector);
 assert(await pg.evaluate(({x,y,selector})=>!!document.elementFromPoint(x,y)?.closest(selector),{x,y,selector}),'uncovered '+selector);
 if(touch)await pg.touchscreen.tap(x,y);else await pg.mouse.click(x,y);await sleep(120)}
async function boot(browser,w,h,touch){const context=await browser.createBrowserContext(),pg=await context.newPage();await pg.setViewport({width:w,height:h,isMobile:touch,hasTouch:touch,deviceScaleFactor:1});await pg.setBypassServiceWorker(true);pg.on('pageerror',e=>errors.push(e.message));
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(()=>!document.getElementById('load')&&typeof ROOM2!=='undefined'&&ROOM2,{timeout:30000});
 await pg.evaluate(()=>{gmMakeSlot();const d=Store.all();S=d.slots[d.cur];S.seen={intro:true};S.snd=true;S.mus=false;save();startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));fpsChecks=6;GM.hour=10;goMap('farm')});await sleep(1800);
 await pg.evaluate(()=>{closeModal();DLG=null;PAUSE=false;HOLD=null;S.name='ต้นกล้า';S.lv=12;S.coins=1600;S.inv=[mkItem('sw',2),mkItem('bow',1),mkGear('armor',2),mkGear('acc',1)];S.eq=0;S.eqA=2;S.eqC=3;S.hp=hpMax();buildPlayerSheets();gridFix();save();hud();P.x=G9.door[0]*T-80;P.y=G9.houseBase*T+75;P.path=null});await sleep(1400);return {context,pg}}
async function shot(pg,name){await pg.$eval('#mBody',e=>e.scrollTop=0);await pg.screenshot({path:path.join(out,name+'.png')})}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE||undefined,args:['--no-sandbox']});try{
 for(const [name,w,h,touch] of [['pc',1366,768,false],['phone',812,330,true],['small',667,375,true]]){const {context,pg}=await boot(browser,w,h,touch);try{
  const hud=await pg.$eval('#hud',e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {width:r.width,height:r.height,border:s.borderTopWidth,shadow:s.boxShadow}});await pg.screenshot({path:path.join(out,name+'-farm.png')});
  await press(pg,'#bSet',touch);assert.equal(await pg.$$eval('.setting155-card',els=>els.length),7,'all seven settings in readable cards');
  const cardSizes=await pg.$$eval('.setting155-card button',bs=>bs.map(b=>({width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height,label:b.getAttribute('aria-label')})));assert(cardSizes.every(s=>s.width>=44&&s.height>=44&&s.label),'card hit areas and labels');
  for(const [id,expr] of [['sOn','SND'],['jOn','!!S.joy'],['ecoB','!!S.eco']]){const before=await pg.evaluate(expr);await press(pg,'#'+id,touch);assert.equal(await pg.evaluate(expr),!before);assert.equal(await pg.$eval('#'+id,e=>e.getAttribute('aria-pressed')),String(!before));assert.equal(await pg.$$eval('.setting155-card',els=>els.length),7,'settings cards survive redraw');await press(pg,'#'+id,touch)}
  await shot(pg,name+'-settings');await press(pg,'#lEn',touch);assert(await pg.$eval('.setting155-card label',e=>e.textContent.length>0));assert(await pg.$eval('#sOn .ui153-label',e=>['On','Off'].includes(e.textContent)));await press(pg,'#lTh',touch);await press(pg,'#mX',touch);
  await press(pg,'#bBag',touch);assert(await pg.$('#equipPortrait'));assert.equal(await pg.$$eval('.slot155-art',cs=>cs.length),3,'all equipped-slot illustrations updated');const equipment=await pg.evaluate(()=>[S.eq,S.eqA,S.eqC].map(i=>S.inv[i].u));assert.equal(await pg.$eval('.slot154',e=>getComputedStyle(e).borderTopWidth),'1px');await press(pg,'#gbSort',touch);assert.deepEqual(await pg.evaluate(()=>[S.eq,S.eqA,S.eqC].map(i=>S.inv[i].u)),equipment);await shot(pg,name+'-bag');
  if(!touch){const from=await pg.$('.gbIt[data-src="bag"][data-i="1"]');await from.scrollIntoView();const a=await from.boundingBox(),to=await pg.$('[data-eqslot="weapon"]'),b=await to.boundingBox();const beforeDrag=await pg.evaluate(()=>S.inv.map(w=>w.u).sort());await pg.mouse.move(a.x+a.width/2,a.y+a.height/2);await pg.mouse.down();await pg.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:12});await sleep(80);
   const ghost=await pg.$eval('body>.gbIt canvas',c=>[...c.getContext('2d').getImageData(0,0,c.width,c.height).data].filter((v,i)=>i%4===3&&v).length);assert(ghost>50,'drag preview carries the item bitmap');await pg.screenshot({path:path.join(out,'pc-drag.png')});await pg.mouse.up();await sleep(150);assert.equal(await pg.evaluate(()=>weapon().type),'bow','real drop equips the bow');assert.deepEqual(await pg.evaluate(()=>S.inv.map(w=>w.u).sort()),beforeDrag,'drag keeps all items')}
  await press(pg,'#mX',touch);
  await pg.evaluate(()=>{goMap('room');closeModal();DLG=null;PAUSE=false;HOLD=null});await sleep(500);await press(pg,'#bDeco',touch);await press(pg,'#deco2 [data-a="shop"]',touch);
  const prices=await pg.$$eval('.shop155-card [data-buy]',bs=>bs.map(b=>({k:b.dataset.buy,text:b.textContent,height:b.getBoundingClientRect().height})));assert.equal(prices.length,9);assert(prices.every(p=>p.height>=44));
  const expected=await pg.evaluate(()=>F2PRICE);assert(prices.every(p=>p.text.includes(String(expected[p.k]))),'original nine shop prices');const k=prices[0].k,before=await pg.evaluate(k=>({coins:S.coins,n:HOME.get().furn2?.[k]||0}),k);
  await press(pg,'[data-buy="'+k+'"]',touch);assert.deepEqual(await pg.evaluate(k=>({coins:S.coins,n:HOME.get().furn2?.[k]||0}),k),{coins:before.coins-expected[k],n:before.n+1});assert.equal(await pg.$$eval('.shop155-card',els=>els.length),9,'cards retained after real purchase');await shot(pg,name+'-shop');await press(pg,'#mX',touch);await press(pg,'#deco2 [data-a="done"]',touch);
  if(touch&&name==='phone'){await press(pg,'#bBag',touch);await pg.setViewport({width:390,height:844,isMobile:true,hasTouch:true,deviceScaleFactor:1});await sleep(200);await shot(pg,'portrait-bag');await press(pg,'#tab154-usable',touch);await press(pg,'#tab154-collection',touch);await press(pg,'#tab154-equipment',touch);await press(pg,'#mX',touch);assert(await pg.evaluate(()=>document.getElementById('rot').classList.contains('hide')===false),'closing portrait bag returns rotation hint');await pg.setViewport({width:w,height:h,isMobile:true,hasTouch:true,deviceScaleFactor:1})}
  assert.equal(hud.border,'1px','quiet single frame');assert(hud.height<=116,'compact status panel');results[name]={viewport:[w,h],hud,settings:cardSizes.length,settingsRedraw:true,english:true,wornItemsKept:true,shopCards:prices.length,pricesKept:true,purchase:true,portrait:name==='phone'};
 }catch(e){errors.push(name+': '+e.message);await pg.screenshot({path:path.join(out,name+'-failure.png')})}finally{await context.close()}}
 }finally{await browser.close()}console.log(JSON.stringify(results));console.log('errors',errors.length,errors);if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
