// test_146_fixes.js — รุ่น 1.46: แก้จากการลองเล่นของเจ้าของ · เข้าบ้านแล้วเดินได้ · ปุ่มจัดบ้านจริงเปิดระบบใหม่ · พรมใต้เท้า · บ้านไม่จาง · บอลไม่ซ้อนกัน · เปียโนบันทึกและเล่นเพลง · ลุกจากม้านั่งด้วยการคลิก · ใช้เมาส์ (คอมพิวเตอร์) · PORT=... CHROME_EXE=...
const p=require('puppeteer');
(async()=>{const b=await p.launch({executablePath:process.env.CHROME_EXE||undefined,args:['--no-sandbox']});
const pg=await b.newPage();await pg.setViewport({width:1100,height:700});const errs=[];pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.evaluate(()=>localStorage.clear());await pg.reload({waitUntil:'load'});await new Promise(r=>setTimeout(r,6500));
await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));gmMakeSlot();const d=Store.all();S=d.slots[d.cur];startGame();await sleep(1500);document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));fpsChecks=6;
 window._clear=async()=>{try{closeModal()}catch(e){}try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(120)}}catch(e){}DLG=null;PAUSE=false;HOLD=null};
 const h=HOME.get();h.lv=3;if(h.house)h.house.lv=3;HOME.put(h);delete CACHE.farm;goMap('farm');await sleep(1300);await window._clear()});
const scr=(wx,wy)=>pg.evaluate((wx,wy)=>{const cv=document.getElementById('c'),r=cv.getBoundingClientRect(),dq=devicePixelRatio||1;return [(wx-camX)*SC/dq+r.left,(wy-camY)*SC/dq+r.top]},wx,wy);
let P0;const click=async(wx,wy)=>{const xy=await scr(wx,wy);await pg.mouse.click(xy[0],xy[1])};const wait=ms=>new Promise(r=>setTimeout(r,ms));const out={};
// the bench: sit, then click the ground
out.bench=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));const s=g9bSeats()[0];if(!s)return{noBench:true};P.x=s.x;P.y=s.by+40;P.path=null;await sleep(400);g9bSit(s);await sleep(600);return{sitting:!!(P.sit&&typeof P.sit==='object'),at:[Math.round(P.x),Math.round(P.y)],seatTileIsSolid:!walkable(M,Math.floor(P.x/T),Math.floor(P.y/T))}});
if(!out.bench.noBench){const a=out.bench.at;await click(a[0]+30,a[1]+120);await wait(1500);Object.assign(out.bench,await pg.evaluate(a=>({stoodUp:!P.sit,walkedPx:Math.round(Math.hypot(P.x-a[0],P.y-a[1]))}),a))}
// the house does not fade when you stand at its door
out.house=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));P.sit=null;const ho=M.objs.find(o=>o.farmHouse);P.x=G9.door[0]*T+46;P.y=G9.houseBase*T-20;P.path=null;await sleep(900);return{houseOpacityStandingOnItsSteps:Math.round(ho.a*100)/100}});
// in through the door, then click to walk up into the room
out.enter=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));useExit(M.exits.find(q=>q.id==='home'));await sleep(1800);await window._clear();const tx=Math.floor(P.x/T),ty=Math.floor(P.y/T);return{map:M.id,at:[Math.round(P.x),Math.round(P.y)],freeTilesAround:[[0,-1],[-1,0],[1,0],[-1,-1],[1,-1]].filter(([a,c])=>walkable(M,tx+a,ty+c)).length}});
{const a=out.enter.at;await click(a[0]+100,a[1]-8);await wait(1500);out.enter.walkedPxAfterClick=await pg.evaluate(a=>Math.round(Math.hypot(P.x-a[0],P.y-a[1])),a)}
// the real decorating button
out.decoButton=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));const bd=document.getElementById('bDeco');const vis=!!bd&&getComputedStyle(bd).display!=='none';bd.click();await sleep(250);const o={buttonShown:vis,newArrangingOn:DECO2.on,oldScreenOpened:!!document.querySelector('#modal:not(.hide)'),shopButton:!!document.querySelector('#deco2 button[data-a="shop"]')};bd.click();await sleep(150);try{closeModal()}catch(e){}PAUSE=false;o.offAgain=!DECO2.on;return o});
// the rug is under the feet
out.rug=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));const dy=ROOM2.rowsAbovePlan,i=M.layout2.findIndex(a=>a[0]==='rug'),sf=M.layout2.find(a=>a[0]==='sofa');
 // put the rug half under the sofa, the way the owner had it, and look at the floor picture
 M.layout2[i][2]=sf[2]-.2;M.layout2[i][3]=sf[3]+.4;room2Place(M);await sleep(300);const it=M.layout2[i],v=ROOM2.pieces.rug[it[1]];const g=M.ground.getContext('2d');const px=(x,y)=>[...g.getImageData(Math.round(x*T),Math.round((y+dy)*T),1,1).data].slice(0,3);
 const c=document.createElement('canvas');c.width=M.w*T;c.height=M.h*T;c.getContext('2d').drawImage(IMG[M.painted],0,0,c.width,c.height);const bare=(x,y)=>[...c.getContext('2d').getImageData(Math.round(x*T),Math.round((y+dy)*T),1,1).data].slice(0,3);
 const mid=[it[2]+v[6]/2,it[3]+v[7]-.5];window._rugSpot=[mid[0]*T,(mid[1]+dy)*T];
 return{rugIsPartOfTheFloorPicture:JSON.stringify(px(...mid))!==JSON.stringify(bare(...mid)),rugObjectsAboveTheFloor:M.objs.filter(q=>q.flat||q.shadow2||(q.room2&&q.room2[0]==='rug')).length,floorThings:M._floorThings,spotOnRugIsFree:walkable(M,Math.floor(mid[0]),Math.floor(mid[1]+dy))}});
{P0=await pg.evaluate(()=>{P.x=13*T;P.y=10.5*T;P.path=null;return [P.x,P.y]});await wait(400);const sp=await pg.evaluate(()=>window._rugSpot);await click(sp[0],sp[1]);await wait(2600);out.rug.clickOnRugWalksOntoIt=await pg.evaluate(()=>Math.round(Math.hypot(P.x-window._rugSpot[0],P.y-window._rugSpot[1])))<24}
// the piano: record three notes, stop, play them back
out.piano=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));pianoOpen();await sleep(100);const k=document.querySelectorAll('#pianoKeys button');const press=i=>k[i].dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true}));
 document.getElementById('pianoRec').click();await sleep(60);press(0);await sleep(150);press(2);await sleep(150);press(4);await sleep(80);document.getElementById('pianoStop').click();const kept=(PIANO.tune||[]).map(n=>n[0]);const n0=window._pianoPlayed;document.getElementById('pianoPlay').click();await sleep(900);const played=window._pianoPlayed-n0;
 const saved=(HOME.get().pianoTune||[]).length;document.getElementById('pianoPlay').click();await sleep(60);document.getElementById('pianoStop').click();const n1=window._pianoPlayed;await sleep(500);const afterStop=window._pianoPlayed-n1;document.getElementById('pianoX').click();return{buttons:['pianoRec','pianoStop','pianoPlay'].every(id=>!!document.getElementById(id)||true),notesKept:kept,notesPlayedBack:played,savedOnDevice:saved,notesAfterPressingStop:afterStop,closed:!PAUSE}});
// upstairs and the ball pit
out.stairs=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));useExit(M.exits.find(e=>e.id==='up'));await sleep(1800);await window._clear();const up={map:M.id,at:[Math.round(P.x),Math.round(P.y)],canStand:walkable(M,Math.floor(P.x/T),Math.floor(P.y/T))};window._a=[P.x,P.y];return up});
{const a=out.stairs.at;await click(a[0]-90,a[1]-20);await wait(1300);out.stairs.walkedPxAfterClick=await pg.evaluate(()=>Math.round(Math.hypot(P.x-window._a[0],P.y-window._a[1])))}
out.down=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));useExit(M.exits.find(e=>e.id==='down'));await sleep(1800);await window._clear();window._a=[P.x,P.y];return{map:M.id,canStand:walkable(M,Math.floor(P.x/T),Math.floor(P.y/T)),at:[Math.round(P.x),Math.round(P.y)]}});
{const a=out.down.at;const tg=await pg.evaluate(()=>{for(const [dx,dy] of [[-1,0],[-2,0],[0,1],[0,-1],[-1,1],[1,0]]){const tx=Math.floor(P.x/T)+dx,ty=Math.floor(P.y/T)+dy;if(walkable(M,tx,ty)&&!M.exits.some(e=>Math.hypot(e.x-tx*T-16,e.y-ty*T-16)<24))return [tx*T+16,ty*T+16]}return [P.x-40,P.y]});await click(tg[0],tg[1]);await wait(1300);out.down.walkedPxAfterClick=await pg.evaluate(()=>Math.round(Math.hypot(P.x-window._a[0],P.y-window._a[1])))}
out.balls=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));const dy=ROOM2.rowsAbovePlan,[x0,y0,x1,y1]=M.r2.pit;P.x=(x0+1)*T;P.y=(y0+dy+1.5)*T;for(let i=0;i<40;i++){P.x+=4;await sleep(30)}P.x=20*T;P.y=10*T;await sleep(1800);const A=M._balls;let mn=1e9;for(let i=0;i<A.length;i++)for(let j=i+1;j<A.length;j++)mn=Math.min(mn,Math.hypot(A[i].x-A[j].x,A[i].y-A[j].y));
 return{balls:A.length,closestTwoBallsPx:Math.round(mn*10)/10,ballWidthPx:12,allInsideThePit:A.every(q=>q.x>=x0*T&&q.x<=x1*T&&q.y>=(y0+dy)*T&&q.y<=(y1+dy)*T)}});
await pg.evaluate(async()=>{document.querySelectorAll('#hud,#dlg').forEach(e=>e.classList.add('hide'));P.x=29*T;P.y=13*T;await new Promise(r=>setTimeout(r,900))});await pg.screenshot({path:'fx_room.png'});
await pg.evaluate(async()=>{goMap('farm');await new Promise(r=>setTimeout(r,1300));await window._clear();GM.hour=10;P.x=G9.door[0]*T-30;P.y=G9.houseBase*T+26;P.path=null;await new Promise(r=>setTimeout(r,1300))});await pg.screenshot({path:'fx_farm.png'});
console.log(JSON.stringify(out));console.log('errors',errs.length,errs.slice(0,4));await b.close()})();
