// Real mouse holds and CDP touch holds: preview colours, transactional drops and cancellation.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=process.env.OUT_DIR||'/tmp/leah-house-164';fs.mkdirSync(out,{recursive:true});
async function state(pg){return pg.evaluate(()=>({layout:JSON.stringify(M.layout2),saved:JSON.stringify(HOME.get()[M.layKey]),stock:JSON.stringify(HOME.get().furn2||{}),preview:D160.preview&&{it:D160.preview.it,er:D160.preview.er},active:!!D160.gesture?.active,paused:PAUSE,hold:DECO2.hold}))}
async function press(pg,sel,touch){const e=await pg.$(sel);assert(e,sel);await e.scrollIntoView();if(touch)await pg.tap(sel);else await pg.click(sel);await sleep(120)}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results={};let pg;
try{for(const [tag,width,height,touch] of [['pc',1366,768,false],['phone',812,375,true],['small',667,375,true],['portrait',393,852,true]]){
 const bc=await browser.createBrowserContext();pg=await bc.newPage();const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.setViewport({width,height,isMobile:touch,hasTouch:touch,deviceScaleFactor:touch?2:1});
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(()=>!$('load')&&ROOM2,{timeout:40000});
 await pg.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.seen={intro:1};S.snd=S.mus=false;ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('room');P.x=11*T;P.y=8.5*T;P.path=null;fpsChecks=6;});await pg.waitForFunction(()=>$('msg').textContent===t('tipStart'),{timeout:10000});if(tag==='portrait'){await pg.setViewport({width:852,height:393,isMobile:true,hasTouch:true,deviceScaleFactor:2});await sleep(300)}await press(pg,'#bDeco',touch);
 const grid=await pg.evaluate(()=>({neutral:true,floorTiles:M.FLOOR.size}));assert(grid.floorTiles>0,'floor grid available; placement verdict is on the moving footprint (1.65)');
 // Prepare a freely rotating piece near the viewport centre. Setup may use APIs; all rotation controls below use real input.
 const source=await pg.evaluate(()=>{const i=M.layout2.findIndex(a=>a[0]==='sofa'),a=M.layout2[i];for(let y=6;y<10;y+=.5)for(let x=8;x<14;x+=.5){const it=[a[0],0,x,y],v=f2View(a[0],0),w=f2View(a[0],1),rot=[a[0],1,f2Snap(x+v[6]/2-w[6]/2),f2Snap(y+v[7]/2-w[7]/2)];if(deco160Valid(it,a)||deco160Valid(rot,a))continue;if(f2Apply(lay=>{lay[i][1]=0;lay[i][2]=x;lay[i][3]=y})){const r=cv.getBoundingClientRect(),d=devicePixelRatio||1;return {i,p:[((x+v[6]/2)*T-camX)*SC/d+r.left,((y+.1+ROOM2.rowsAbovePlan)*T-camY)*SC/d+r.top]}}}throw Error('no rotatable setup')});
 await sleep(100);const target=await pg.evaluate(i=>{const a=M.layout2[i],v=f2View(a[0],a[1]),r=cv.getBoundingClientRect(),d=devicePixelRatio||1;for(let oy=-v[5]/T+.2;oy<v[7];oy+=.2){const x=a[2]+v[6]/2,y=a[3]+oy,p=[(x*T-camX)*SC/d+r.left,((y+ROOM2.rowsAbovePlan)*T-camY)*SC/d+r.top];if(p[0]>6&&p[1]>6&&p[0]<innerWidth-6&&p[1]<innerHeight-6&&document.elementFromPoint(...p)===cv&&deco2Hit(x,y)===i)return p}throw Error('visible sofa required')},source.i);
 if(touch)await pg.touchscreen.tap(...target);else await pg.mouse.click(...target);await sleep(150);assert.equal(await pg.evaluate(()=>DECO2.sel),source.i);assert(await pg.$('#deco164 [data-a="turn"]'));
 const keep=await state(pg);await pg.evaluate(()=>say(t('d2Wall')));await press(pg,'#deco164 [data-a="turn"]',touch);assert.equal(await pg.evaluate(()=>$('msg').textContent),'','previous placement warning cleared by rotation');assert.equal((await state(pg)).layout,keep.layout);assert.equal((await state(pg)).saved,keep.saved);assert(await pg.evaluate(()=>D164.rotation&&!D164.rotation.er));
 const fits=await pg.evaluate(()=>{const d=$('deco164').getBoundingClientRect();return {inside:d.left>=0&&d.top>=0&&d.right<=innerWidth&&d.bottom<=innerHeight,buttons:[...$('deco164').querySelectorAll('button')].every(b=>{const r=b.getBoundingClientRect();return r.height>=48&&r.width>=48}),aboveBar:d.bottom<=$('deco2').getBoundingClientRect().top}});assert(fits.inside&&fits.buttons&&fits.aboveBar,JSON.stringify(fits));await pg.screenshot({path:path.join(out,tag+'-rotate.png')});
 await press(pg,'#cancel164',touch);assert.equal((await state(pg)).layout,keep.layout);assert.equal((await state(pg)).saved,keep.saved);
 await press(pg,'#deco164 [data-a="turn"]',touch);const expected=await pg.evaluate(()=>D164.rotation.it);await press(pg,'#confirm164',touch);assert.deepEqual(await pg.evaluate(i=>M.layout2[i],source.i),expected);assert.equal((await state(pg)).layout,(await state(pg)).saved);assert.equal((await state(pg)).stock,keep.stock);
 // A floor-valid original with a blocked quarter-turn must not be confirmable.
 const blocked=await pg.evaluate(i=>{const a=M.layout2[i];for(let y=0;y<M.r2.grid.length;y+=.5)for(let x=0;x<M.w;x+=.5){const it=[a[0],0,x,y],v=f2View(a[0],0),w=f2View(a[0],1),r=[a[0],1,f2Snap(x+v[6]/2-w[6]/2),f2Snap(y+v[7]/2-w[7]/2)];if(!deco160Valid(it,a)&&deco160Valid(r,a)&&f2Apply(lay=>{lay[i][1]=0;lay[i][2]=x;lay[i][3]=y})){deco2UI();return true}}return false},source.i);assert(blocked,'blocked rotation fixture');
 const stable=await state(pg);await press(pg,'#deco164 [data-a="turn"]',touch);assert(await pg.evaluate(()=>$('confirm164').disabled&&!!D164.rotation.er));await press(pg,'#confirm164',touch);assert.equal((await state(pg)).layout,stable.layout);assert.equal((await state(pg)).saved,stable.saved);await press(pg,'#cancel164',touch);
 // Leaving with another preview must keep the last confirmed angle.
 await press(pg,'#deco164 [data-a="turn"]',touch);const confirmed=await state(pg);await press(pg,'#deco2 [data-a="done"]',touch);assert.equal((await state(pg)).layout,confirmed.layout);assert.equal((await state(pg)).saved,confirmed.saved);assert.equal(await pg.$('#deco164'),null);
 const saved=confirmed.saved;await pg.reload({waitUntil:'load'});await pg.waitForFunction(()=>!$('load'),{timeout:40000});assert.equal(await pg.evaluate(()=>JSON.stringify(HOME.get().room2)),saved);assert.deepEqual(errors,[]);results[tag]={grid,previewDoesNotSave:true,cancel:true,confirmedAndReloaded:true,blockedRotationRejected:true,fits,errors:0};await bc.close();
}console.log(JSON.stringify(results));console.log('errors 0');}catch(e){console.error(e);if(pg&&!pg.isClosed())await pg.screenshot({path:path.join(out,'failure.png')});process.exitCode=1}finally{await browser.close()}})();
