// Codex: GM appearance draft -> real animated player, shared portraits, persistence and missing-art fallback.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=process.env.OUT_DIR||'/tmp/leah-look-169';fs.mkdirSync(out,{recursive:true});
async function press(p,s,touch){await p.waitForSelector(s,{visible:true});const b=await p.$(s);await b.scrollIntoView();await(touch?p.tap(s):p.click(s));await sleep(140)}
async function open(p,touch){await press(p,'#gmBtn',touch);await press(p,'#gmLook169',touch);await p.waitForSelector('#look169-preview',{visible:true})}
async function choose(p,f,n,touch){await press(p,'[data-look-field="'+f+'"][data-look-value="'+n+'"]',touch)}
const snapshot=p=>p.evaluate(()=>JSON.stringify({kid:S.kid,hc:S.hc,ec:S.ec,coins:S.coins,lv:S.lv,exp:S.exp,inv:S.inv,eq:S.eq,eqA:S.eqA,eqC:S.eqC,equipment:S.equipment157,look:S.appearance169}));
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results=[];let p;try{
for(const [name,width,height,touch,missing] of [['pc',1366,768,false,false],['phone',812,330,true,false],['small',667,375,true,false],['missing-base',812,375,true,true]]){
 const bc=await browser.createBrowserContext();p=await bc.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width,height,hasTouch:touch,isMobile:touch,deviceScaleFactor:touch?2:1});
 if(missing){await p.setRequestInterception(true);p.on('request',r=>/kid-bob-(stand|walk)\.png/.test(r.url())?r.abort():r.continue())}
 await p.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await p.waitForFunction(()=>!$('load')&&ROOM2,{timeout:40000});
 await p.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.age=30;S.snd=S.mus=false;S.seen={intro:1};ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('farm');P.path=P.act=null;fpsChecks=6});await sleep(2600);
 const before=await snapshot(p),original=await p.evaluate(()=>PS.stand.toDataURL());await open(p,touch);
 if(missing){assert(await p.$eval('#look169-apply',b=>b.disabled));assert(await p.$eval('#look169-status',e=>/ภาพยังไม่พร้อม/.test(e.innerText)));await press(p,'#look169-reset',touch);await press(p,'#look169-apply',touch);assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);assert.equal(await snapshot(p),before);assert.deepEqual(errors,[]);results.push({name,fallback:true,errors:0});await bc.close();continue}
 const controls=await p.$$eval('#look169-apply,#look169-cancel,#look169-reset,.look169-turn button',bs=>bs.map(b=>{const r=b.getBoundingClientRect();return {id:b.id,w:r.width,h:r.height,inside:r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}}));assert(controls.every(b=>b.w>=48&&b.h>=48&&b.inside),JSON.stringify(controls));
 const prev=await p.$eval('#look169-preview',c=>c.toDataURL());await choose(p,'hair',2,touch);await choose(p,'face',1,touch);await choose(p,'hc',5,touch);await choose(p,'ec',3,touch);assert.notEqual(await p.$eval('#look169-preview',c=>c.toDataURL()),prev);assert.equal(await snapshot(p),before);assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);
 const afterScroll=await p.$$eval('#look169-apply,#look169-cancel,#look169-reset,.look169-heading h2',bs=>bs.map(b=>{const r=b.getBoundingClientRect();return{top:r.top,bottom:r.bottom}}));assert(afterScroll.every(r=>r.top>=0&&r.bottom<=height),'header and commands stay visible after choosing scrolled colours: '+JSON.stringify(afterScroll));
 await p.screenshot({path:path.join(out,name+'-studio.png')});await press(p,'#look169-cancel',touch);assert.equal(await snapshot(p),before);await open(p,touch);await choose(p,'hair',2,touch);await choose(p,'face',1,touch);await choose(p,'hc',5,touch);await choose(p,'ec',3,touch);
 await press(p,'#look169-right',touch);await press(p,'#look169-walk',touch);const frame1=await p.$eval('#look169-preview',c=>c.toDataURL());await sleep(240);assert.notEqual(await p.$eval('#look169-preview',c=>c.toDataURL()),frame1,'animated preview changes frame');await press(p,'#look169-apply',touch);
 const applied=await p.evaluate(()=>({look:S.appearance169,stored:Store.all().slots[Store.all().cur].appearance169,stand:PS.stand.toDataURL(),preview:crSheet(S.kid,S.house,S.hc,S.ec,S.appearance169).toDataURL(),peer:othSheets(S.kid,S.house,S.hc,S.ec,S.appearance169).stand.toDataURL(),portrait:$('hudPortrait').toDataURL()}));assert.deepEqual(applied.look,{v:1,hair:2,face:1,hc:5,ec:3});assert.deepEqual(applied.stored,applied.look);assert.notEqual(applied.stand,original);assert.equal(applied.stand,applied.preview);assert.equal(applied.peer,applied.stand);
 const state=JSON.parse(await snapshot(p));delete state.look;assert.deepEqual(state,JSON.parse(before));
 // Every row/frame retains the same lower body. Hair, expression and eye-colour choices change real sheet pixels.
 const art=await p.evaluate(()=>{const pixels=c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data,changed=(a,b)=>{const x=pixels(a),y=pixels(b);let n=0;for(let i=0;i<x.length;i++)if(x[i]!==y[i])n++;return n},crop=(c,x,y,w,h)=>{const v=document.createElement('canvas');v.width=w;v.height=h;v.getContext('2d').drawImage(c,x,y,w,h,0,0,w,h);return v};let nonempty=0,bodyDifferences=0;const bodies={stand:recolorKey(IMG['s_kid-bob'],HOUSES[S.house].h),walk:recolorKey(IMG['w_kid-bob'],HOUSES[S.house].h)};const faces=[],eyes=[],hair=[];
  for(let h=0;h<3;h++){const a={v:1,hair:h,face:0,hc:5,ec:0},s=look169Sheets(a,S.house);hair.push(s.stand.toDataURL());faces.push([1,2].map(f=>changed(crop(s.stand,0,0,64,64),crop(look169Sheets({...a,face:f},S.house).stand,0,0,64,64))));eyes.push(changed(s.stand,look169Sheets({...a,ec:3},S.house).stand));for(let dir=0;dir<8;dir++)for(let f=-1;f<6;f++){const w=f>=0,x=w?f*64:dir*64,y=w?dir*64:0,c=w?s.walk:s.stand;bodyDifferences+=changed(crop(c,x,y+38,64,26),crop(w?bodies.walk:bodies.stand,x,y+38,64,26));const p=pixels(crop(c,x,y,64,64));let count=0;for(let j=3;j<p.length;j+=4)if(p[j]>0)count++;if(count>200)nonempty++}}
  const blue=pixels(crop(look169Sheets({v:1,hair:2,face:0,hc:5,ec:3},S.house).stand,0,0,64,23));let greenIris=0;for(let i=0;i<blue.length;i+=4)if(blue[i+3]>100&&blue[i+1]>blue[i]*1.18&&blue[i+1]>blue[i+2]*1.12)greenIris++;
  return {greenIris,faces,eyes,hairstyles:new Set(hair).size,nonempty,bodyDifferences}});assert(art.faces.flat().every(n=>n>0),JSON.stringify(art));assert(art.eyes.every(n=>n>0));assert.equal(art.greenIris,0,'both green irises must change to the selected blue');assert.equal(art.hairstyles,3);assert.equal(art.nonempty,168);assert.equal(art.bodyDifferences,0);
 // Record drawImage calls from the real world renderer while actual movement keys are held.
 await p.evaluate(()=>{MONS=[];gmGhost(true);P.x=14*T;P.y=14*T;P.path=P.act=null;window.walk169=[];const old=ctx.drawImage;ctx.drawImage=function(im,...args){if(im===PS.walk)walk169.push([Math.round(args[0]/64),Math.round(args[1]/64)]);return old.call(this,im,...args)}});
 const poses=[['ArrowDown'],['ArrowDown','ArrowRight'],['ArrowRight'],['ArrowUp','ArrowRight'],['ArrowUp'],['ArrowUp','ArrowLeft'],['ArrowLeft'],['ArrowDown','ArrowLeft']];const distance=[];
 for(const ks of poses){const a=await p.evaluate(()=>[P.x,P.y]);for(const k of ks)await p.keyboard.down(k);await sleep(330);for(const k of ks)await p.keyboard.up(k);await sleep(80);const z=await p.evaluate(()=>[P.x,P.y]);distance.push(Math.hypot(z[0]-a[0],z[1]-a[1]))}assert(distance.every(n=>n>10));const motion=await p.evaluate(()=>({directions:[...new Set(walk169.map(x=>x[1]))].sort(),frames:[...new Set(walk169.map(x=>x[0]))].sort()}));assert.equal(motion.directions.length,8);assert(motion.frames.length>=2);await p.screenshot({path:path.join(out,name+'-world.png')});
 // Studio appearance also reaches the equipped portrait; other slots and the original creator stay independent.
 await press(p,'#bBag',touch);assert(await p.$('#equipPortrait'));await press(p,'#mX',touch);await p.evaluate(()=>{const d=Store.all();window.gmSlot169=d.cur;d.slots.push(newSave({name:'Other',kid:0,house:0,age:30}));Store.put(d)});await press(p,'#bSet',touch);await press(p,'#swP',touch);await press(p,'#pk>.pn:last-of-type',touch);await press(p,'#pGo',touch);await sleep(500);assert(await p.evaluate(()=>!S.appearance169));assert.notEqual(await p.evaluate(()=>PS.stand.toDataURL()),applied.stand);await press(p,'#bSet',touch);await press(p,'#swP',touch);await press(p,'#pk>.pn:first-child',touch);await press(p,'#pGo',touch);await sleep(500);assert.deepEqual(await p.evaluate(()=>S.appearance169),applied.look);
 await p.reload({waitUntil:'load'});await p.waitForFunction(()=>!$('load')&&ROOM2);await p.evaluate(()=>{S=Store.all().slots[Store.all().cur];S.gmInit=1;S.snd=S.mus=false;S.seen={intro:1};ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal()});await sleep(2600);assert.deepEqual(await p.evaluate(()=>S.appearance169),applied.look);assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),applied.stand);
 await press(p,'#bSet',touch);await press(p,'#lEn',touch);await press(p,'#mX',touch);await open(p,touch);assert(await p.$eval('#look169',e=>e.textContent.includes('Hairstyle')));await press(p,'#look169-reset',touch);assert(await p.evaluate(()=>!!S.appearance169),'reset is still a draft');await press(p,'#look169-apply',touch);assert(await p.evaluate(()=>!S.appearance169));assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);assert.deepEqual(errors,[]);results.push({name,controls,art,motion,saveReload:true,restore:true,errors:0});await bc.close();
}console.log(JSON.stringify(results));console.log('errors 0')}catch(e){console.error(e);if(p&&!p.isClosed()){console.log(await p.evaluate(()=>({version:VERSION,look:S?.appearance169,modal:$('mBody')?.textContent.slice(-500)})));await p.screenshot({path:path.join(out,'failure.png')})}process.exitCode=1}finally{await browser.close()}})();
