// test_137_room.js — รุ่น 1.37: ฉากในบ้านใหม่ขั้น 1 · เดินถึงทุกห้อง · ของวางตามแปลน · ปุ่มใช้ของ · เปียโน · ออกจากบ้าน · MISSING=1 = ทดสอบตอนไฟล์หาย · PORT=... CHROME_EXE=...
const p=require('puppeteer');
(async()=>{const b=await p.launch({executablePath:process.env.CHROME_EXE||undefined,args:['--no-sandbox']});
const pg=await b.newPage();await pg.setViewport({width:1000,height:640,isMobile:true,hasTouch:true,deviceScaleFactor:1});const errs=[];pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.evaluate(()=>localStorage.clear());await pg.reload({waitUntil:'load'});await new Promise(r=>setTimeout(r,6000));
const R=await pg.evaluate(async()=>{const o={version:VERSION,filesReady:!!(ROOM2&&IMG.roomL1&&IMG.furnPlain)};const sleep=ms=>new Promise(r=>setTimeout(r,ms));gmMakeSlot();const d=Store.all();S=d.slots[d.cur];startGame();await sleep(1500);document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));fpsChecks=6;
 const clear=async()=>{try{closeModal()}catch(e){}try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(120)}}catch(e){}DLG=null;PAUSE=false;HOLD=null};
 goMap('room');await sleep(1200);await clear();o.room={map:M.id,newRoom:!!M.room2,size:[M.w,M.h],painted:M.painted||null,things:M.objs.filter(q=>q.room2).length,playerTile:[Math.floor(P.x/T),Math.floor(P.y/T)],playerCanStand:walkable(M,Math.floor(P.x/T),Math.floor(P.y/T))};
 if(!M.room2)return o;
 // can you walk from the door into every room? (flood over the walkable tiles)
 const st=[Math.floor(P.x/T),Math.floor(P.y/T)],seen=new Set([key(st[0],st[1])]),q=[st];while(q.length){const [x,y]=q.pop();for(const [a,c] of [[x+1,y],[x-1,y],[x,y+1],[x,y-1]]){const k=key(a,c);if(!seen.has(k)&&walkable(M,a,c)){seen.add(k);q.push([a,c])}}}
 const dy=ROOM2.rowsAbovePlan,rooms={K:'kitchen',D:'dining',L:'living',H:'corridor',B:'bedroom',T:'bathroom',S:'storage'},reach={},total={};let freeTiles=0,unreach=0;
 for(let y=0;y<M.r2.grid.length;y++)for(let x=0;x<M.r2.grid[y].length;x++){const c=M.r2.grid[y][x],nm=rooms[c];if(!walkable(M,x,y+dy))continue;freeTiles++;if(!seen.has(key(x,y+dy)))unreach++;if(nm){total[nm]=(total[nm]||0)+1;if(seen.has(key(x,y+dy)))reach[nm]=(reach[nm]||0)+1}}
 o.walk={freeTiles,cannotReach:unreach,reachedOfFreeTilesByRoom:Object.fromEntries(Object.keys(total).map(k=>[k,(reach[k]||0)+'/'+total[k]]))};
 // no furniture foot outside the floor, none on a wall
 o.thingsOnFloor=M.objs.filter(q=>q.room2).every(q=>{const [k,r,tx,ty]=q.room2,v=ROOM2.pieces[k][r%ROOM2.pieces[k].length];for(const [a,c] of [[tx+.1,ty+.1],[tx+v[6]-.1,ty+v[7]-.1]]){const ch=(M.r2.grid[Math.floor(c)]||'')[Math.floor(a)];if(!ch||ch==='#'||ch===' '||ch==='P')return false}return true});
 // the big button beside the bed and the piano
 const near=async k=>{const ob=M.objs.find(q=>q.room2&&q.room2[0]===k);let best=null;for(let r=1;r<6&&!best;r++)for(let dy2=-r;dy2<=r&&!best;dy2++)for(let dx=-r;dx<=r&&!best;dx++){const tx=Math.floor(ob.x/T)+dx,ty=Math.floor(ob.y/T)+dy2;if(walkable(M,tx,ty)&&seen.has(key(tx,ty))&&Math.hypot(Math.max(ob.useRect[0]-tx*T-16,0,tx*T+16-ob.useRect[2]),Math.max(ob.useRect[1]-ty*T-16,0,ty*T+16-ob.useRect[3]))<30)best=[tx*T+16,ty*T+16]}if(!best)return{noSpot:true};P.x=best[0];P.y=best[1];P.path=null;await sleep(600);const c=anyNear();return{button:c&&c.k,word:document.getElementById('atkL').textContent}};
 o.besideBed=await near('bed');o.besidePiano=await near('piano');autoAct();await sleep(400);const keys=document.querySelectorAll('#pianoKeys button');o.piano={opened:!!document.getElementById('pianoBox'),keys:keys.length};
 if(keys.length){for(const kb of [...keys].slice(0,3))kb.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true}));await sleep(200);o.piano.notesPlayed=window._pianoPlayed||0;document.getElementById('pianoX').click();await sleep(200);o.piano.closed=!document.getElementById('pianoBox')&&!PAUSE}
 openDeco();await sleep(150);o.newDecoratingOpens=!!(typeof DECO2!=='undefined'&&DECO2.on)&&!(typeof DEC!=='undefined'&&DEC.on);openDeco();await sleep(100);o.andCloses=!DECO2.on;
 window._spawn=M.spawnDefault;return o});
await pg.evaluate(async()=>{document.querySelectorAll('#hud,#act,#dlg').forEach(e=>e.classList.add('hide'));P.x=13*T;P.y=9.5*T;P.path=null;await new Promise(r=>setTimeout(r,1200))});await pg.screenshot({path:'rm_1.png'});
if(R.room&&R.room.newRoom){R.leave=await pg.evaluate(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));goMap('farm');await sleep(1300);try{for(let i=0;i<12&&DLG;i++){if(typeof dlgNext==='function')dlgNext();else DLG=null;await sleep(120)}}catch(e){}DLG=null;PAUSE=false;goMap('room');await sleep(1000);DLG=null;PAUSE=false;const e=M.exits[0];P.x=e.x;P.y=e.y-40;P.path=null;await sleep(400);P.path=[[e.x,e.y]];let out=null;for(let k=0;k<20&&!out;k++){await sleep(250);if(M.id!=='room')out=M.id}return{walkedOutTo:out}})}
console.log(JSON.stringify(R));console.log('errors',errs.length,errs.slice(0,4));await b.close()})();
