// Real context-balloon clicks/taps; existing furniture/farm/NPC/exit actions and stale-target guards.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const out=process.env.OUT_DIR||'/tmp/leah-context-167';fs.mkdirSync(out,{recursive:true});const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function press(pg,selector,touch){await pg.waitForSelector(selector,{visible:true});if(touch)await pg.tap(selector);else await pg.click(selector);await sleep(180)}
async function clear(pg){await pg.evaluate(()=>{DLG=null;$('dlg').classList.add('hide');$('pianoX')?.click();closeModal();PAUSE=false;P.path=null;P.act=null;P.sit=null;HOLD=null})}
async function nearFurniture(pg,kind){return pg.evaluate(kind=>{const o=M.objs.find(o=>o.fu?.k===kind);if(!o)throw Error('missing '+kind);const pt=o.usePt||[o.x,o.y];for(let dy=-80;dy<=80;dy+=8)for(let dx=-80;dx<=80;dx+=8){const x=pt[0]+dx,y=pt[1]+dy;if(blockedAt(M,x,y))continue;P.x=x;P.y=y;P.path=null;P.act=null;if(anyNear()?.target===o&&ctx167Choice()?.target===o){CTX167.at=0;return {x,y}}}throw Error('no reachable '+kind)},kind)}
// Place the fixture on reachable ground; actions below still use real buttons.
async function approach(pg,source,action){await pg.evaluate(({source,action})=>{const o=source==='seat'?g9bSeats()[0]:source==='plot'?M.plots[0]:M[source];if(!o)throw Error('missing '+source);for(let dy=-72;dy<=72;dy+=6)for(let dx=-72;dx<=72;dx+=6){const x=o.x+dx,y=(o.by??o.y)+dy;if(blockedAt(M,x,y))continue;P.x=x;P.y=y;P.path=P.act=null;const c=ctx167Choice();if(c?.k===action&&(source==='seat'||c.target===o)){CTX167.at=0;return}}throw Error('no reachable '+source)},{source,action})}
async function inspect(pg){await pg.waitForFunction(()=>!$('context167')?.hidden&&!!CTX167.current);await sleep(220);return pg.evaluate(()=>{const b=$('context167'),r=b.getBoundingClientRect(),icon=b.querySelector('svg');return {label:b.textContent,aria:b.getAttribute('aria-label'),icon:b.dataset.icon,action:b.dataset.action,box:{x:r.x,y:r.y,w:r.width,h:r.height},inside:r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,svgPaths:icon?.querySelectorAll('path,rect,circle').length||0,buttons:document.querySelectorAll('#context167:not([hidden])').length,overlaps:['hud','topR','mmw','act'].filter(id=>{const e=$(id),q=e.getBoundingClientRect();return getComputedStyle(e).display!=='none'&&r.left<q.right&&r.right>q.left&&r.top<q.bottom&&r.bottom>q.top})}})}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results={};let pg;try{
for(const [tag,width,height,touch,missing] of [['pc',1366,768,false,false],['phone',812,330,true,false],['small-missing-icons',667,375,true,true]]){
 const bc=await browser.createBrowserContext();pg=await bc.newPage();const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.setViewport({width,height,isMobile:touch,hasTouch:touch,deviceScaleFactor:touch?2:1});if(missing){await pg.setRequestInterception(true);pg.on('request',r=>/ui-icons.png|ui-quietgold-icons.webp/.test(r.url())?r.abort():r.continue())}
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(()=>!$('load')&&ROOM2,{timeout:40000});await pg.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.seen={intro:1};S.snd=S.mus=false;ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();const h=HOME.get();h.lv=2;HOME.put(h);goMap('farm');goMap('room');P.path=null;P.act=null;fpsChecks=6});await sleep(2500);const r={furniture:{}};
 for(const [kind,icon] of [['bed','bed'],['sofa','sofa'],['piano','piano'],['stove','pot'],['shelf','book'],['bath','bath'],['toilet','toilet'],['wash','wash']]){
  await clear(pg);await nearFurniture(pg,kind);await pg.evaluate(()=>{S.hp=10;S.fdone=null;P._bathT=0});const q=await inspect(pg);assert.equal(q.icon,icon);assert(q.inside&&q.box.w>=48&&q.box.h>=48&&q.svgPaths>0&&q.buttons===1,JSON.stringify(q));assert(q.aria&&!q.aria.includes('undefined'));assert.deepEqual(q.overlaps,[],kind+' popup clear of HUD');if(kind==='bed')await pg.screenshot({path:path.join(out,tag+'-bed.png')});
  await press(pg,'#context167',touch);const effect=await pg.evaluate(kind=>{if(kind==='bed')return S.hp===hpMax()&&S.fdone.sleep===1;if(kind==='sofa')return S.fdone.cuddle===1;if(kind==='piano')return !!$('pianoBox')&&$('context167').hidden;if(kind==='stove')return !$('modal').classList.contains('hide')&&$('context167').hidden;if(kind==='shelf')return S.fdone.read===1;if(kind==='bath')return S.hp>10;if(kind==='toilet')return P._needWash===1;return !P._needWash},kind);assert(effect,kind+' action happened');r.furniture[kind]=q;
 }
 await clear(pg);await nearFurniture(pg,'bed');await inspect(pg);await press(pg,'#bDeco',touch);assert(await pg.evaluate(()=>$('context167').hidden));await press(pg,'#deco2 [data-a="done"]',touch);await inspect(pg);await press(pg,'#bSet',touch);assert(await pg.evaluate(()=>$('context167').hidden));await press(pg,'#lEn',touch);await press(pg,'#mX',touch);assert.equal((await inspect(pg)).aria,'Sleep');if(!touch){await pg.evaluate(()=>{S.hp=10;S.fdone=null});await pg.keyboard.press('e');assert.equal(await pg.evaluate(()=>S.hp),await pg.evaluate(()=>hpMax()));await sleep(450);await inspect(pg);r.keyboardE=true}
 // A click on a stale balloon must not apply its saved callback to a far-away target.
 await pg.evaluate(()=>{S.fdone=null;S.hp=10;P.x=4*T;P.y=11*T;P.path=null;$('context167').click()});assert.equal(await pg.evaluate(()=>S.hp),10);r.staleClickRefused=true;
 // The explicit doorway action uses the game's existing transition and appears before auto-crossing distance.
 await clear(pg);await pg.evaluate(()=>{const e=M.exits.find(e=>e.id==='door');exitCool=0;P.x=e.x;P.y=e.y-30;P.path=null;CTX167.at=0});let q=await inspect(pg);assert.equal(q.icon,'door');await pg.screenshot({path:path.join(out,tag+'-door.png')});await press(pg,'#context167',touch);await pg.waitForFunction(()=>M.id==='farm',{timeout:10000});await clear(pg);r.door=true;
 // Reach the selling crate with actual keyboard walking, then use the new balloon.
 const walk=await pg.evaluate(()=>{const o=M.crate;for(const [dx,dy,k] of [[-1,0,'ArrowRight'],[1,0,'ArrowLeft'],[0,1,'ArrowUp']]){const x=o.x+dx*75,y=o.y+10+dy*75;if(blockedAt(M,x,y)||blockedAt(M,x-dx*35,y-dy*35))continue;P.x=x;P.y=y;P.path=null;P.act=null;return {x,y,key:k}}throw Error('crate approach')});await sleep(300);await pg.keyboard.down(walk.key);try{await pg.waitForFunction(()=>CTX167.current?.k==='actSell',{timeout:4000})}finally{await pg.keyboard.up(walk.key)}const P0=await pg.evaluate(()=>[P.x,P.y]);assert(Math.hypot(P0[0]-walk.x,P0[1]-walk.y)>10);q=await inspect(pg);assert.equal(q.icon,'coin');await pg.screenshot({path:path.join(out,tag+'-crate.png')});await press(pg,'#context167',touch);assert(await pg.evaluate(()=>!$('modal').classList.contains('hide')));await clear(pg);r.walkThenSell=true;
 await approach(pg,'seat','actSit');q=await inspect(pg);assert.equal(q.icon,'sofa');await press(pg,'#context167',touch);assert(await pg.evaluate(()=>!!P.sit));await clear(pg);r.bench=true;
 await approach(pg,'fishSpot','actFish');q=await inspect(pg);assert.equal(q.icon,'rod');await press(pg,'#context167',touch);assert(await pg.evaluate(()=>FISHING.on&&$('context167').hidden));await pg.evaluate(()=>{FISHING.on=false;FISHING.st='idle'});await clear(pg);r.fishing=true;
 await pg.evaluate(()=>{const h=HOME.get();delete h.plots[M.plots[0].i];h.seeds[Object.keys(CROPS)[0]]=3;HOME.put(h)});await approach(pg,'plot','actPlant');q=await inspect(pg);assert.equal(q.icon,'sprout');await press(pg,'#context167',touch);await press(pg,'[data-sd]',touch);q=await inspect(pg);assert.equal(q.icon,'can');await press(pg,'#context167',touch);assert(await pg.evaluate(()=>!!HOME.get().plots[M.plots[0].i].w));await clear(pg);r.plantThenWater=true;
 await pg.evaluate(()=>{goMap('h9');P.path=null});await sleep(500);await clear(pg);await pg.evaluate(()=>{const n=M.npcs[0];for(let dy=14;dy<55;dy+=6)for(let dx=-30;dx<31;dx+=6){const x=n.x+dx,y=n.y+dy;if(blockedAt(M,x,y))continue;P.x=x;P.y=y;P.path=null;if(ctx167Choice()?.target===n)return}throw Error('NPC approach')});q=await inspect(pg);assert.equal(q.icon,'talk');await press(pg,'#context167',touch);assert(await pg.evaluate(()=>!!DLG||PAUSE));await clear(pg);r.talk=true;
 await approach(pg,'board','actBoard');q=await inspect(pg);assert.equal(q.icon,'search');await pg.screenshot({path:path.join(out,tag+'-board.png')});await press(pg,'#context167',touch);assert(await pg.evaluate(()=>!$('modal').classList.contains('hide')));await clear(pg);r.board=true;
 await pg.evaluate(()=>{goMap('hunt1');S.age=30;MONS=[];for(const c of M.crystals){c.awake=true;for(let a=0;a<24;a++){const x=c.x+Math.cos(a*Math.PI/12)*24,y=c.y+Math.sin(a*Math.PI/12)*24;if(blockedAt(M,x,y))continue;P.x=x;P.y=y;P.path=P.act=null;window.inspectCrystal167=c;return}}throw Error('crystal approach')});q=await inspect(pg);assert.equal(q.action,'actExplore');assert.equal(q.icon,'search');const coins=await pg.evaluate(()=>S.coins);await press(pg,'#context167',touch);assert(await pg.$eval('#mBody',e=>/already awake/.test(e.innerText)));assert.equal(await pg.evaluate(()=>S.coins),coins);await clear(pg);r.crystalInspect=true;
 await pg.evaluate(()=>{P.x=2*T;P.y=2*T;P.path=null;P.act=null;CTX167.at=0});await sleep(250);assert(await pg.evaluate(()=>$('context167').hidden));assert.deepEqual(errors,[]);r.errors=0;results[tag]=r;await bc.close();
}console.log(JSON.stringify(results));console.log('errors 0');}catch(e){console.error(e);if(pg&&!pg.isClosed()){console.log(await pg.evaluate(()=>({map:M.id,player:[P.x,P.y],near:anyNear()&&{k:anyNear().k,target:!!anyNear().target},current:CTX167.current&&{k:CTX167.current.k,label:CTX167.current.label},pause:PAUSE,dlg:!!DLG})));await pg.screenshot({path:path.join(out,'failure.png')})}process.exitCode=1}finally{await browser.close()}})();
