// Codex: GM-only unarmed sprite, real menu and movement, saves and independent fallbacks.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=process.env.OUT_DIR||'/tmp/leah-swordsman-170';fs.mkdirSync(out,{recursive:true});
const url='http://localhost:'+(process.env.PORT||8775)+'/?gm';
async function press(p,s,touch=false){await p.waitForSelector(s,{visible:true});await (await p.$(s)).scrollIntoView();await(touch?p.tap(s):p.click(s));await sleep(120)}
async function enter(p){await p.waitForFunction(()=>!$('load')&&ROOM2,{timeout:45000});await p.evaluate(()=>{if(!Store.all().slots.length)gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.snd=S.mus=false;S.joy=true;S.seen={intro:1};ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('farm');P.path=P.act=null;fpsChecks=6});await sleep(2700)}
async function open(p,touch=false){await press(p,'#gmBtn',touch);await press(p,'#gmSwordsman170',touch)}
const important=p=>p.evaluate(()=>JSON.stringify({kid:S.kid,age:S.age,job:S.job,lv:S.lv,coins:S.coins,inv:S.inv,eq:S.eq,eqA:S.eqA,eqC:S.eqC,equipment:S.equipment157,appearance:S.appearance169}));
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results=[];let p;try{
 for(const [name,width,height,touch,fail] of (process.env.ONLY_RACE?[]:[['pc',1366,768,false,''],['phone',812,330,true,''],['missing',812,375,true,'missing'],['corrupt',1100,700,false,'corrupt'],['wrong-size',1100,700,false,'size']])){
  const bc=await browser.createBrowserContext();p=await bc.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width,height,isMobile:touch,hasTouch:touch});
  if(fail){await p.setBypassServiceWorker(true);await p.setRequestInterception(true);p.on('request',r=>r.url().includes('swordsman-170.webp')?(fail==='missing'?r.abort():r.respond({status:200,contentType:'image/webp',body:fail==='size'?fs.readFileSync(path.join(__dirname,'icon-192.png')):'not an image'})):r.continue())}
  await p.goto(url,{waitUntil:'load'});await enter(p);const before=await important(p),original=await p.evaluate(()=>PS.stand.toDataURL());await open(p,touch);
  if(fail){await p.evaluate(()=>{S.gmSprite170='swordsman';save();buildPlayerSheets()});await p.waitForFunction(()=>SW170.error&&!SW170.pending);assert(await p.$eval('#sw170-use',b=>b.disabled));assert(await p.$eval('#sw170-status',b=>b.textContent.includes('โหลดภาพไม่ได้')));await press(p,'#sw170-restore',touch);assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);assert.equal(await important(p),before);assert.deepEqual(errors,[]);results.push({name,fallback:true,errors:0});await bc.close();continue}
  await p.waitForFunction(()=>SW170.sheets&&!$('sw170-use').disabled);
  const bounds=await p.$$eval('#sw170-use,#sw170-restore,#sw170-cancel',bs=>bs.map(b=>{const r=b.getBoundingClientRect();return{inside:r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,height:r.height}}));assert(bounds.every(b=>b.inside&&b.height>=48),JSON.stringify(bounds));
  assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);await p.screenshot({path:path.join(out,name+'-menu.png')});await press(p,'#sw170-cancel',touch);assert.equal(await important(p),before);assert(await p.evaluate(()=>!S.gmSprite170));await open(p,touch);await press(p,'#sw170-use',touch);assert(await p.evaluate(()=>PS.gmSprite170&&S.gmSprite170==='swordsman'));assert.equal(await important(p),before);assert.equal(await p.evaluate(()=>Store.all().slots[Store.all().cur].gmSprite170),'swordsman');const applied=await p.evaluate(()=>PS.stand.toDataURL());assert.notEqual(applied,original);
  const frames=await p.evaluate(()=>{let count=0;const c=document.createElement('canvas');c.width=c.height=64;const g=c.getContext('2d');for(let r=0;r<8;r++)for(let f=-1;f<6;f++){g.clearRect(0,0,64,64);g.drawImage(f<0?PS.stand:PS.walk,f<0?r*64:f*64,f<0?0:r*64,64,64,0,0,64,64);const a=g.getImageData(0,0,64,64).data;let n=0;for(let j=3;j<a.length;j+=4)if(a[j]>80)n++;if(n>100)count++}return count});assert.equal(frames,56);
  await p.evaluate(()=>{gmGhost(true);P.x=40*T;P.y=26*T;P.path=P.act=null;window.draw170=[];const old=ctx.drawImage;ctx.drawImage=function(im,...a){if(im===PS.walk)draw170.push([a[0]/64,a[1]/64]);return old.call(this,im,...a)}});
  const poses=[['ArrowDown'],['ArrowDown','ArrowRight'],['ArrowRight'],['ArrowUp','ArrowRight'],['ArrowUp'],['ArrowUp','ArrowLeft'],['ArrowLeft'],['ArrowDown','ArrowLeft']],vectors=[[0,1],[1,1],[1,0],[1,-1],[0,-1],[-1,-1],[-1,0],[-1,1]],distances=[];const cdp=touch?await p.createCDPSession():null;
  for(let i=0;i<8;i++){const a=await p.evaluate(()=>[P.x,P.y]);if(touch){const r=await p.$eval('#joy',e=>{const r=e.getBoundingClientRect();return{x:r.left+56,y:r.top+56}});const [x,y]=vectors[i],n=Math.hypot(x,y);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x,y:r.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+35*x/n,y:r.y+35*y/n,id:1}]})}else for(const k of poses[i])await p.keyboard.down(k);await sleep(420);if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else for(const k of poses[i])await p.keyboard.up(k);await sleep(90);const z=await p.evaluate(()=>[P.x,P.y]);distances.push(Math.round(Math.hypot(z[0]-a[0],z[1]-a[1])))}assert(distances.every(n=>n>10),JSON.stringify(distances));
  const motion=await p.evaluate(()=>({rows:[...new Set(draw170.map(x=>x[1]))],columns:[...new Set(draw170.map(x=>x[0]))]}));assert.equal(motion.rows.length,8);assert.equal(motion.columns.length,6);
  await p.evaluate(()=>{gmGhost(false);P.row=0;P.path=null;P.moving=false;GM.hour=12;P.x=40*T;P.y=25*T;S.peb=false;PEB.on=false;S.pet=-1});await sleep(300);await p.screenshot({path:path.join(out,name+'-farm.png')});
  await p.evaluate(()=>{goMap('room');P.path=P.act=null;P.row=0});await sleep(700);assert(await p.evaluate(()=>PS.gmSprite170));await p.screenshot({path:path.join(out,name+'-house.png')});
  // Same blocked movement with either sprite: changing art must not change collision.
  const collision=await p.evaluate(()=>{const samples=[];for(let y=2;y<M.h-2;y++)for(let x=2;x<M.w-2;x++){const px=x*T+T/2,py=y*T+T/2;if(!blockedAt(M,px,py)&&blockedAt(M,px+T,py)){samples.push([px,py]);if(samples.length===10)return samples}}return samples});
  assert(collision&&collision.length>0,'room needs a real wall fixture');await p.evaluate(([x,y])=>{P.x=x;P.y=y;P.path=P.act=null},collision[0]);await p.keyboard.down('ArrowRight');await sleep(900);await p.keyboard.up('ArrowRight');const hit=await p.evaluate(()=>({x:P.x,y:P.y,blocked:blockedAt(M,P.x,P.y)}));assert(!hit.blocked);assert(hit.x>=collision[0][0]&&hit.x<collision[0][0]+25,'new art must stop before the wall');
  assert.equal(await important(p),before);
  await p.reload({waitUntil:'load'});await enter(p);await p.waitForFunction(()=>PS.gmSprite170,{timeout:15000});assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),applied);
  await p.evaluate(()=>{const d=Store.all();d.slots.push(newSave({name:'Other',kid:0,house:0,age:30}));Store.put(d)});await press(p,'#bSet',touch);await press(p,'#swP',touch);await press(p,'#pk>.pn:last-child',touch);await sleep(400);assert(await p.evaluate(()=>!PS.gmSprite170&&!S.gmSprite170));await press(p,'#bSet',touch);await press(p,'#swP',touch);await press(p,'#pk>.pn:first-child',touch);await sleep(400);assert(await p.evaluate(()=>PS.gmSprite170));
  await open(p,touch);await press(p,'#sw170-restore',touch);assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);assert(await p.evaluate(()=>!S.gmSprite170&&!Store.all().slots[Store.all().cur].gmSprite170));assert.equal(await important(p),before);assert.deepEqual(errors,[]);results.push({name,frames,bounds,motion,distances,collisionSamples:collision?.length||0,saveReload:true,slotIsolation:true,restore:true,errors:0});await bc.close();
 }
 // Same-document picker fixture keeps the old image request alive; real Settings switching above reloads and cancels it.
 {const bc=await browser.createBrowserContext();p=await bc.newPage();await p.setBypassServiceWorker(true);const errors=[];p.on('pageerror',e=>errors.push(e.message));const held=[];let released=false;const respond=r=>r.respond({status:200,contentType:'image/webp',body:fs.readFileSync(path.join(__dirname,'swordsman-170.webp'))});await p.setRequestInterception(true);p.on('request',r=>{if(r.url().includes('swordsman-170.webp')){if(released)respond(r);else held.push(r)}else r.continue()});await p.goto(url,{waitUntil:'load'});await enter(p);
 await p.evaluate(()=>{const d=Store.all();d.slots.push(newSave({name:'Normal',kid:0,house:0,age:30}));Store.put(d);S.gmSprite170='swordsman';save();buildPlayerSheets()});for(let i=0;!held.length&&i<40;i++)await sleep(50);assert(held.length,'delayed asset requested');await p.evaluate(()=>openPicker(Store.all()));await press(p,'#pk>.pn:last-child');const original=await p.evaluate(()=>PS.stand.toDataURL());released=true;await Promise.all(held.map(respond));await p.waitForFunction(()=>SW170.sheets);await sleep(200);assert(await p.evaluate(()=>!gmOn()&&!PS.gmSprite170));assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original);await p.evaluate(()=>{S.gmSprite170='swordsman';buildPlayerSheets()});assert.equal(await p.evaluate(()=>PS.stand.toDataURL()),original,'ordinary slot cannot opt into GM art');assert.deepEqual(errors,[]);results.push({name:'delayed-load',ordinarySlotUnaffected:true,errors:0});await bc.close()}
 console.log(JSON.stringify(results));console.log('errors 0');
 }catch(e){console.error(e);if(p&&!p.isClosed())console.log(await p.evaluate(()=>({swError:SW170.error,swPending:!!SW170.pending,swReady:!!SW170.sheets,gm:gmOn()})));if(p&&!p.isClosed())await p.screenshot({path:path.join(out,'failure.png')});process.exitCode=1}finally{await browser.close()}})();
