// Real mouse holds and CDP touch holds: preview colours, transactional drops and cancellation.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=process.env.OUT_DIR||'/tmp/leah-house-165';fs.mkdirSync(out,{recursive:true});
async function state(pg){return pg.evaluate(()=>({layout:JSON.stringify(M.layout2),saved:JSON.stringify(HOME.get()[M.layKey]),stock:JSON.stringify(HOME.get().furn2||{}),preview:D160.preview&&{it:D160.preview.it,er:D160.preview.er},active:!!D160.gesture?.active,paused:PAUSE,hold:DECO2.hold}))}
async function scr(pg,wx,wy){return pg.evaluate(([x,y])=>{const r=cv.getBoundingClientRect(),d=devicePixelRatio||1;return [(x*T-camX)*SC/d+r.left,((y+ROOM2.rowsAbovePlan)*T-camY)*SC/d+r.top]},[wx,wy])}
async function points(pg,touch,condition,index){return pg.evaluate(({touch,condition,index})=>{
 const ix=index??M.layout2.findIndex(a=>a[0]==='plant'),a=M.layout2[ix],v=f2View(a[0],a[1]),r=cv.getBoundingClientRect(),d=devicePixelRatio||1;
 const xy=(x,y,lift)=>[(x*T-camX)*SC/d+r.left,((y+ROOM2.rowsAbovePlan)*T-camY)*SC/d+r.top+(lift?54:0)];
 const visible=p=>p[0]>6&&p[1]>6&&p[0]<innerWidth-6&&p[1]<innerHeight-6&&document.elementFromPoint(...p)===cv;
 let from=null;for(const oy of [v[7]/2,.2,-.4,-.8]){const p=xy(a[2]+v[6]/2,a[3]+oy,false);if(visible(p)&&deco2Hit(a[2]+v[6]/2,a[3]+oy)===ix){from={p,ox:v[6]/2,oy};break}}if(!from)return {error:'source not visible',a};
 for(let y=0;y<M.r2.grid.length;y+=.5)for(let x=0;x<M.w;x+=.5){const it=[a[0],a[1],x,y],p=xy(x+from.ox,y+from.oy,touch);if(!visible(p)||Math.hypot(x-a[2],y-a[3])<1)continue;
  const quick=f2Valid(it,a),er=quick||deco160Valid(it,a),px=P.x/T,py=P.y/T-ROOM2.rowsAbovePlan;
  const ok=condition==='valid'?!er:condition==='player'?er==='d2Block'&&x<=px&&px<x+v[6]&&y<=py&&py<y+v[7]:condition==='path'?quick===''&&er==='d2Block'&&Math.hypot(x-px,y-py)>3:er===condition;
  if(ok)return {index:ix,from:from.p,to:p,it,ox:from.ox,oy:from.oy};
 }return {error:'no visible '+condition,a,from,player:[P.x/T,P.y/T-ROOM2.rowsAbovePlan],probe:[6,6.5].map(y=>{const p=xy(P.x/T+from.ox,y+from.oy,touch);return {y,p,top:document.elementFromPoint(...p)?.outerHTML.slice(0,150),er:deco160Valid([a[0],a[1],P.x/T,y],a)}})};
 },{touch,condition,index})}
async function press(pg,sel,touch){const e=await pg.$(sel);assert(e,sel);await e.scrollIntoView();if(touch)await pg.tap(sel);else await pg.click(sel);await sleep(120)}
async function down(pg,cdp,p,touch){if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p[0],y:p[1],id:1}]});else{await pg.mouse.move(...p);await pg.mouse.down()}}
async function move(pg,cdp,a,b,touch){if(touch){for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a[0]+(b[0]-a[0])*i/10,y:a[1]+(b[1]-a[1])*i/10,id:1}]});await sleep(15)}}else await pg.mouse.move(...b,{steps:12});await sleep(180)}
async function up(pg,cdp,touch,cancel=false){if(touch)await cdp.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});else await pg.mouse.up();await sleep(150)}
async function colour(pg){return pg.evaluate(()=>{const p=D160.preview;if(!p)return {green:0,red:0};const a=p.it,v=f2View(a[0],a[1]),x=Math.max(0,Math.floor((a[2]*T-camX)*SC)),y=Math.max(0,Math.floor(((a[3]+ROOM2.rowsAbovePlan)*T-camY)*SC));
 const w=Math.min(cv.width-x,Math.ceil(v[6]*T*SC)),h=Math.min(cv.height-y,Math.ceil(v[7]*T*SC));if(w<=0||h<=0)return {green:0,red:0};const data=ctx.getImageData(x,y,w,h).data;let green=0,red=0;
 for(let i=0;i<data.length;i+=4){if(data[i+1]>data[i]+45&&data[i+1]>data[i+2]+25)green++;if(data[i]>data[i+1]+75&&data[i]>data[i+2]+65)red++}return {green,red};})}
// 1.65 regression: the user's plant/table pictures need full sprite bounds, and only the candidate may give a coloured verdict.
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results={};let pg;
try{for(const [tag,width,height,touch] of [['pc',1366,768,false],['phone',667,375,true]]){
 const bc=await browser.createBrowserContext();pg=await bc.newPage();const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.setViewport({width,height,isMobile:touch,hasTouch:touch,deviceScaleFactor:touch?2:1});const cdp=await pg.target().createCDPSession();
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(()=>!$('load')&&ROOM2,{timeout:40000});await pg.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.seen={intro:1};S.snd=S.mus=false;ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('room');P.x=11*T;P.y=8.5*T;P.path=null;fpsChecks=6;});await pg.waitForFunction(()=>$('msg').textContent===t('tipStart'),{timeout:10000});await press(pg,'#bDeco',touch);
 const neutral=await pg.evaluate(()=>{const strokes=[],fills=[],stroke=ctx.strokeRect,fill=ctx.fillRect;ctx.strokeRect=function(){strokes.push(this.strokeStyle);return stroke.apply(this,arguments)};ctx.fillRect=function(){fills.push(this.fillStyle);return fill.apply(this,arguments)};try{deco164Grid()}finally{ctx.strokeRect=stroke;ctx.fillRect=fill}return {strokes:[...new Set(strokes)],fills: fills.length,count:strokes.length,tiles:M.FLOOR.size}});assert.equal(neutral.fills,0,'no background green/red fill');assert.equal(neutral.strokes.length,1,'one neutral grid colour');assert(neutral.count>0);assert(!neutral.strokes.some(s=>/65dfa0|ed6675|f56e79/.test(s)));results[tag]={neutral,pieces:{}};
 for(const kind of ['plant','roundtable']){
  await pg.evaluate(kind=>{const i=M.layout2.findIndex(a=>a[0]===kind),a=M.layout2[i];for(let y=5;y<10;y+=.5)for(let x=8;x<14;x+=.5){const it=[kind,a[1],x,y];if(!deco160Valid(it,a)&&f2Apply(lay=>{lay[i][2]=x;lay[i][3]=y})){DECO2.sel=null;DECO2.hold=null;deco2UI();return}}throw Error('visible piece setup '+kind)},kind);await sleep(150);
  const ix=await pg.evaluate(kind=>M.layout2.findIndex(a=>a[0]===kind),kind),p=await points(pg,touch,'valid',ix);assert(!p.error,JSON.stringify(p));const keep=await state(pg);await pg.evaluate(()=>say(t('d2Wall')));await down(pg,cdp,p.from,touch);if(touch)await pg.waitForFunction(()=>D160.gesture?.active,{timeout:3000});await move(pg,cdp,p.from,p.to,touch);
  const pr=await state(pg);assert.equal(await pg.evaluate(()=>$('msg').textContent),'','previous wall warning cleared for the new candidate');assert.equal(pr.preview.er,'');assert.equal(pr.saved,keep.saved);const pixels=await colour(pg);assert(pixels.green>5);
  const bounds=await pg.evaluate(()=>{const it=D160.preview.it,v=f2View(it[0],it[1]),frame=deco165SpriteBounds(it),record=[],old=ctx.drawImage;ctx.drawImage=function(...args){if(args[1]===v[0]&&args[2]===v[1]&&args[3]===v[2]&&args[4]===v[3])record.push(args.slice(5));return old.apply(this,args)};try{deco2Draw()}finally{ctx.drawImage=old}const [x,y,w,h]=frame,baseTop=(it[3]+ROOM2.rowsAbovePlan)*T-camY;
   let gold=0;for(const [cx,cy] of [[x-2,y-2],[x+w+2,y-2],[x-2,y+h+2],[x+w+2,y+h+2]]){const sx=Math.floor((cx-3)*SC),sy=Math.floor((cy-3)*SC),size=Math.ceil(7*SC);if(sx<0||sy<0||sx+size>cv.width||sy+size>cv.height)continue;const data=ctx.getImageData(sx,sy,size,size).data;for(let j=0;j<data.length;j+=4)if(data[j]>220&&data[j+1]>180&&data[j+1]>data[j+2]+30)gold++}return {frame,drawn:record,aboveBase:baseTop-y,gold}});assert(bounds.drawn.some(a=>JSON.stringify(a)===JSON.stringify(bounds.frame)),'gold brackets surround actual rendered sprite');assert(bounds.aboveBase>15,'full frame includes art above the floor base');assert(bounds.gold>5,'gold frame visibly drawn');await pg.screenshot({path:path.join(out,tag+'-'+kind+'-green.png')});await up(pg,cdp,touch);assert.equal((await state(pg)).layout,(await state(pg)).saved);assert.notEqual((await state(pg)).layout,keep.layout);
  // Invalid wall drop remains red and cannot be saved, independent of the neutral background.
  const start=await points(pg,touch,'valid',ix);assert(!start.error,JSON.stringify(start));const saved=await state(pg);await down(pg,cdp,start.from,touch);if(touch)await pg.waitForFunction(()=>D160.gesture?.active,{timeout:3000});else await pg.mouse.move(start.from[0]+7,start.from[1]);const bad=await points(pg,touch,'d2Wall',ix);assert(!bad.error,JSON.stringify(bad));await move(pg,cdp,start.from,bad.to,touch);assert.equal((await state(pg)).preview.er,'d2Wall');assert((await colour(pg)).red>5);await pg.screenshot({path:path.join(out,tag+'-'+kind+'-red.png')});await up(pg,cdp,touch);assert.equal((await state(pg)).layout,saved.layout);assert.equal((await state(pg)).saved,saved.saved);results[tag].pieces[kind]={bounds,greenPixels:pixels.green,validSaved:true,wallRefused:true};
 }
 assert.deepEqual(errors,[]);await bc.close();}console.log(JSON.stringify(results));console.log('errors 0');}catch(e){console.error(e);if(pg&&!pg.isClosed())await pg.screenshot({path:path.join(out,'failure.png')});process.exitCode=1}finally{await browser.close()}})();
