// Codex: mouse/touch exploration, fast ranged attacks, charge collision and unobscured art.
const assert=require('node:assert/strict'),fs=require('node:fs'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out='/tmp/leah-crystal-163';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']});const results=[];
try{for(const touch of [false,true]){
 const ctxB=await browser.createBrowserContext(),pg=await ctxB.newPage(),errors=[];await pg.setViewport(touch?{width:667,height:375,isMobile:true,hasTouch:true}:{width:1366,height:768});pg.on('pageerror',e=>errors.push(e.message));
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(()=>!document.getElementById('load')&&typeof CRYSTAL_BARRIER_R==='number');
 await pg.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.mus=S.snd=false;S.seen={intro:1};startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));goMap('hunt1')});await sleep(1800);
 const press=async sel=>{await pg.waitForSelector(sel,{visible:true});const e=await pg.$(sel);await e.scrollIntoView();if(touch)await pg.tap(sel);else await pg.click(sel);await sleep(200)};
 await pg.evaluate(()=>{closeModal();DLG=null;PAUSE=false});if(touch){await press('#bSet');await press('#lEn');await press('#mX');assert.equal(await pg.evaluate(()=>LANG),'en')}
 const setup=await pg.evaluate(()=>{closeModal();DLG=null;PAUSE=false;for(const c of M.crystals)for(let a=0;a<24;a++){
  const rad=a*Math.PI/12,p=[c.x+Math.cos(rad)*40,c.y+Math.sin(rad)*40];if(blockedAt(M,...p))continue;const path=findPath(M,...p,c.x,c.y+14);if(!path||!path.length)continue;
  window.c163=c;window.origin163=p;P.x=p[0];P.y=p[1];P.path=P.target=P.act=null;MONS=[];return {c:[c.x,c.y],p,awake:c.awake}}
 });assert(setup);await sleep(400);assert.equal(await pg.$eval('#bCtx200 .w200',e=>e.textContent),touch?'Explore':'สำรวจ');assert.notEqual(await pg.$eval('#atkL',e=>e.textContent),touch?'Explore':'สำรวจ','2.00: the big button stays the attack for 10+, the small button explores');
 const hp=await pg.evaluate(()=>S.hp);await pg.evaluate(()=>{hurtPlayer(999);useJob('provoke');useSkill()});assert.equal(await pg.evaluate(()=>S.hp),hp);
 await press('#bCtx200');await pg.waitForSelector('.ch button',{visible:true,timeout:6000});const endDist=await pg.evaluate(()=>Math.hypot(P.x-c163.x,P.y-c163.y));assert(endDist<=29,'Explore walks from the edge to the crystal');
 await pg.evaluate(()=>{closeModal();DLG=null;PAUSE=true;P.x=c163.x+24;P.y=c163.y;P.path=P.target=P.act=null;S.crystals[M.id]=[c163.id];c163.awake=true});
 const ranged=await pg.evaluate(()=>{const c=c163,res=[];for(const mode of ['enemy','friendly']){const target={x:c.x+100,y:c.y,hp:5000,max:5000,kind:'slime',happy:false};const s=mode==='enemy'?{k:'rock',from:'b',x:c.x-100,y:c.y-30,vx:4000,vy:0,dmg:999,life:2}:{k:'bow',from:'p',x:c.x-100,y:c.y-14,tx:target,sp:4000,dmg:999,type:'bow'};updShot(s,.05);res.push({mode,done:!!s.done,distance:Math.hypot(s.x-c.x,s.y+(mode==='enemy'?30:14)-c.y),hp:target.hp})}return res});
 for(const r of ranged){assert(r.done,'crossing shot stops: '+r.mode);assert(Math.abs(r.distance-48)<.01);assert.equal(r.hp,5000)}
 const dash=await pg.evaluate(()=>{const c=c163,m=mkMon('bat',c.x-70,c.y,1);m.act=11;m.actT=.55;m.vx=800;m.vy=0;m.ax=c.x+100;m.ay=c.y;m.st='chase';m.stun=0;MONS=[m];P.x=c.x+24;P.y=c.y;PAUSE=false;updateMonsters(.2);PAUSE=true;return {d:Math.hypot(m.x-c.x,m.y-c.y),act:m.act}});assert(dash.d>=48,'fast enemy charge cannot tunnel through');assert.equal(dash.act,0);
 const chase=await pg.evaluate(()=>{const c=c163,m=mkMon('slime',c.x+65,c.y,1);m.st='chase';m.taunt=performance.now()+5000;MONS=[m];updateMonsters(.01);return {state:m.st,taunt:m.taunt}});assert.equal(chase.state,'wander');assert.equal(chase.taunt,0);
 // Draw the real dome over the current scene: it must change background pixels but none in the character box.
 const art=await pg.evaluate(()=>{MONS=[];render(100);const x=Math.max(0,Math.ceil((P.x-20-camX)*SC)+1),y=Math.max(0,Math.ceil((P.y-64-camY)*SC)+1),w=Math.min(cv.width-x,Math.floor(40*SC)-3),h=Math.min(cv.height-y,Math.floor(68*SC)-3);const before=ctx.getImageData(x,y,w,h).data,all=ctx.getImageData(0,0,cv.width,cv.height).data;crystalBarrierDome163(100);const after=ctx.getImageData(x,y,w,h).data,all2=ctx.getImageData(0,0,cv.width,cv.height).data;let changed=0,blocked=0;for(let i=0;i<before.length;i++)if(before[i]!==after[i])blocked++;for(let i=0;i<all.length;i+=4)if(all[i]!==all2[i]||all[i+1]!==all2[i+1]||all[i+2]!==all2[i+2])changed++;return {blocked,changed}});assert.equal(art.blocked,0);assert(art.changed>30,'dome is visible on the scene');await pg.screenshot({path:out+'/'+(touch?'touch':'pc')+'-barrier.png'});
 await pg.evaluate(()=>{PAUSE=false;closeModal();DLG=null;P.path=null;P.x=c163.x+24;P.y=c163.y});await sleep(400);const coins=await pg.evaluate(()=>S.coins);await press('#bCtx200');assert(await pg.$eval('#mBody',e=>/คริสตัลตื่นแล้ว|already awake/.test(e.innerText)));await press('#mX');assert.equal(await pg.evaluate(()=>S.coins),coins,'awake inspection grants no new rewards in step 1');
 // Leaving the barrier restores actual attacks; no global attack lock.
 await pg.evaluate(()=>{closeModal();PAUSE=false;DLG=null;const nest=M.spawns.find(p=>!blockedAt(M,p.x,p.y)&&(M.crystals||[]).every(c=>Math.hypot(p.x-c.x,p.y-c.y)>150));if(!nest)throw Error('No outside attack test spot');P.x=nest.x;P.y=nest.y;P.path=P.target=P.act=null;const m=mkMon('slime',nest.x+12,nest.y,1);m.hp=m.max=5000;m.stun=99;MONS=[m];window.target163=m;S.eq=S.inv.findIndex(i=>i.type==='sw')});await sleep(400);await press('#bAtk');await sleep(1400);assert(await pg.evaluate(()=>target163.hp<5000),'outside attack works');
 // A child's automatic proximity quiz must cancel the unfinished Explore action.
 await pg.evaluate(()=>{closeModal();DLG=null;PAUSE=false;S.age=7;S.seen={intro:1,first:1,floor:1};S.crystals[M.id]=[];c163.awake=false;MONS=[];P.x=c163.x;P.y=c163.y+40;P.path=P.target=P.act=null});await sleep(400);await press('#bAtk');await pg.waitForSelector('.ch button',{visible:true});
 const answer=await pg.evaluate(()=>QBANK.find(q=>q.id===lastQ).answer),wrong=[0,1,2,3].filter(n=>n!==answer);await press('.ch button[data-i="'+wrong[0]+'"]');await press('.ch button[data-i="'+wrong[1]+'"]');await press('#qClose');await sleep(600);assert(await pg.evaluate(()=>$('modal').classList.contains('hide')&&c163.awake),'Close stays closed after the child proximity quiz');
 assert.deepEqual(errors,[]);results.push({touch,endDist,ranged,dash,chase,art,childCloseStaysClosed:true,errors:0});await ctxB.close();
}console.log(JSON.stringify(results));console.log('errors 0')}catch(e){console.error(e);process.exitCode=1}finally{await browser.close()}})();
