// Codex: real mouse/touch glissando, chords, audio lifecycle, recording and piano colour isolation.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=process.env.OUT_DIR||'/tmp/leah-piano-168';fs.mkdirSync(out,{recursive:true});
async function press(p,s,touch){await p.waitForSelector(s,{visible:true});await(touch?p.tap(s):p.click(s));await sleep(120)}
async function open(p,touch){await p.evaluate(()=>{DLG=null;closeModal();PAUSE=false;const o=M.objs.find(o=>o.fu?.k==='piano'),pt=o.usePt||[o.x,o.y];for(let dy=-80;dy<=80;dy+=8)for(let dx=-80;dx<=80;dx+=8){const x=pt[0]+dx,y=pt[1]+dy;if(blockedAt(M,x,y))continue;P.x=x;P.y=y;P.path=P.act=null;if(anyNear()?.target===o)return}throw Error('piano not reachable')});await p.waitForFunction(()=>CTX167.current?.k==='actPiano'&&!$('context167').hidden);await sleep(300);await press(p,'#context167',touch);await p.waitForSelector('#pianoKeys button',{visible:true})}
async function points(p){return p.$$eval('#pianoKeys button',bs=>bs.map(b=>{const r=b.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height*.72,w:r.width,h:r.height}}))}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results=[];let p;
try{for(const [name,width,height,touch,missing] of [['pc',1366,768,false,false],['phone',812,330,true,false],['small-fallback',667,375,true,true]]){
 const context=await browser.createBrowserContext();p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width,height,hasTouch:touch,isMobile:touch,deviceScaleFactor:touch?2:1});
 if(missing){await p.setRequestInterception(true);p.on('request',r=>/ui-quietgold-(frames|icons)\.webp/.test(r.url())?r.abort():r.continue())}
 await p.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await p.waitForFunction(()=>!$('load')&&ROOM2,{timeout:40000});
 await p.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.seen={intro:1};S.snd=S.mus=false;ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('room');fpsChecks=6;P.path=P.act=null;
  window.audio168=[];const orig=BaseAudioContext.prototype.createOscillator;BaseAudioContext.prototype.createOscillator=function(){const o=orig.call(this),start=o.start.bind(o),stop=o.stop.bind(o),r={hz:0,stopped:false};o.start=function(...args){r.hz=o.frequency.value;audio168.push(r);return start(...args)};o.stop=function(...args){r.stopped=true;return stop(...args)};return o};
 });await sleep(2500);await open(p,touch);let pts=await points(p);assert(pts.every(q=>q.w>=48&&q.h>=90));
 const layout=await p.evaluate(()=>({colours:[...document.querySelectorAll('#pianoKeys button')].map(b=>{const s=getComputedStyle(b);return{background:s.backgroundImage,frame:s.borderImageSource,text:s.color}}),controls:[...document.querySelectorAll('#pianoBox footer button')].map(b=>{const r=b.getBoundingClientRect();return {id:b.id,h:r.height,visible:r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth}})}));
 assert.equal(new Set(layout.colours.map(c=>c.background)).size,8);assert(layout.colours.every(c=>c.frame==='none'&&c.text==='rgb(50, 35, 62)'));assert(layout.controls.every(c=>c.h>=48&&c.visible));
 const cdp=await p.createCDPSession(),send=async(type,ps)=>{await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:ps.map(([i,n])=>({x:pts[n].x,y:pts[n].y,id:i,radiusX:2,radiusY:2,force:1}))});await sleep(80)};
 const down=async n=>touch?send('touchStart',[[1,n]]):(await p.mouse.move(pts[n].x,pts[n].y),p.mouse.down());
 const move=async n=>touch?send('touchMove',[[1,n]]):p.mouse.move(pts[n].x,pts[n].y);
 const up=async()=>touch?send('touchEnd',[]):p.mouse.up();
 await press(p,'#pianoRec',touch);await down(0);await sleep(450);
 assert.equal(await p.evaluate(()=>PIANO.rec.notes.length),1,'holding does not machine-gun the same note');assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),1);assert.equal(await p.evaluate(()=>audio168.filter(o=>!o.stopped).length),1);
 await p.screenshot({path:path.join(out,name+'-held.png')});
 // One sparse browser move crosses all seven intervening notes, then returns without lifting.
 await move(7);await sleep(80);await move(0);await sleep(80);await up();await press(p,'#pianoStop',touch);
 const tune=await p.evaluate(()=>HOME.get().pianoTune);assert.deepEqual(tune.map(n=>n[0]),[0,1,2,3,4,5,6,7,6,5,4,3,2,1,0]);assert(tune[0][2]>=400);assert(tune.every(n=>n[2]>=30));assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),0);assert(await p.evaluate(()=>audio168.every(o=>o.stopped)));
 const freq=await p.evaluate(()=>audio168.slice(0,8).map(o=>Math.round(o.hz)));assert.deepEqual(freq,[262,294,330,349,392,440,494,523]);
 // Leaving the keyboard stops a held note. Re-entering sounds it once again, and cancellation releases it.
 await press(p,'#pianoRec',touch);await down(3);const r=await p.$eval('#pianoKeys',b=>{const r=b.getBoundingClientRect();return{y:r.top-10}});
 if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pts[3].x,y:r.y,id:1}]});else await p.mouse.move(pts[3].x,r.y);await sleep(80);
 assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),0);await move(3);assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),1);
 if(touch)await send('touchCancel',[]);else await up();assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),0);await press(p,'#pianoStop',touch);assert.deepEqual(await p.evaluate(()=>PIANO.tune.map(n=>n[0])),[3,3]);
 if(touch){await press(p,'#pianoRec',touch);await send('touchStart',[[1,0],[2,4]]);assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),2);await sleep(100);await send('touchMove',[[1,1],[2,4]]);assert.deepEqual(await p.$$eval('#pianoKeys .held168',bs=>bs.map(b=>+b.dataset.note)),[1,4]);await send('touchEnd',[[2,4]]);assert.equal(await p.$$eval('#pianoKeys .held168',x=>x.length),1);await send('touchEnd',[]);await press(p,'#pianoStop',touch);assert(await p.evaluate(()=>audio168.every(o=>o.stopped)))}
 // Store three deliberate notes via real taps, play once, then stop/close an ongoing replay.
 await press(p,'#pianoRec',touch);for(const n of [0,2,4]){await down(n);await sleep(65);await up();await sleep(65)}await press(p,'#pianoStop',touch);assert.deepEqual(await p.evaluate(()=>PIANO.tune.map(n=>n[0])),[0,2,4]);
 const before=await p.evaluate(()=>window._pianoPlayed);await press(p,'#pianoPlay',touch);await sleep(900);assert.equal(await p.evaluate(before=>window._pianoPlayed-before,before),3);assert(await p.evaluate(()=>audio168.every(o=>o.stopped)));
 await press(p,'#pianoPlay',touch);await press(p,'#pianoStop',touch);let n=await p.evaluate(()=>window._pianoPlayed);await sleep(700);assert.equal(await p.evaluate(()=>window._pianoPlayed),n);assert(await p.evaluate(()=>audio168.every(o=>o.stopped)));
 await press(p,'#pianoPlay',touch);await press(p,'#pianoX',touch);n=await p.evaluate(()=>window._pianoPlayed);await sleep(700);assert.equal(await p.evaluate(()=>window._pianoPlayed),n);assert(await p.evaluate(()=>!PAUSE&&!$('pianoBox')&&audio168.every(o=>o.stopped)));
 await open(p,touch);assert.deepEqual(await p.evaluate(()=>PIANO.tune.map(n=>n[0])),[0,2,4]);await down(5);await p.evaluate(()=>dispatchEvent(new Event('blur')));assert(await p.evaluate(()=>audio168.every(o=>o.stopped)));await up();await press(p,'#pianoX',touch);
 // Reload persisted notes and exercise an older two-column recording and English labels.
 await p.reload({waitUntil:'load'});await p.waitForFunction(()=>!$('load')&&ROOM2);await p.evaluate(()=>{S=Store.all().slots[Store.all().cur];S.gmInit=1;S.snd=S.mus=false;S.seen={intro:1};ensureDaily();S.daily.seen=1;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('room');P.path=P.act=null});await sleep(2500);assert.deepEqual(await p.evaluate(()=>HOME.get().pianoTune.map(n=>n[0])),[0,2,4]);
 await press(p,'#bSet',touch);await press(p,'#lEn',touch);await press(p,'#mX',touch);await open(p,touch);assert.equal(await p.$eval('#pianoKeys button',b=>b.getAttribute('aria-label')),'Do');await p.evaluate(()=>{PIANO.tune=[[0,0],[2,120],[4,240]]});n=await p.evaluate(()=>window._pianoPlayed||0);await press(p,'#pianoPlay',touch);await sleep(1100);assert.equal(await p.evaluate(()=>window._pianoPlayed)-n,3);await p.screenshot({path:path.join(out,name+'-english.png')});await press(p,'#pianoX',touch);
 assert.deepEqual(errors,[]);results.push({name,colours:8,glissando:15,holdMs:tune[0][2],frequencies:freq,chords:touch,recordReload:true,legacyReplay:true,controls:layout.controls,errors:0});await context.close();
}console.log(JSON.stringify(results));console.log('errors 0')}catch(e){console.error(e);if(p&&!p.isClosed())await p.screenshot({path:path.join(out,'failure.png')});process.exitCode=1}finally{await browser.close()}})();
