// Real mouse holds and CDP touch holds: preview colours, transactional drops and cancellation.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=process.env.OUT_DIR||'/tmp/leah-house-166';fs.mkdirSync(out,{recursive:true});
async function state(pg){return pg.evaluate(()=>({layout:JSON.stringify(M.layout2),saved:JSON.stringify(HOME.get()[M.layKey]),stock:JSON.stringify(HOME.get().furn2||{}),preview:D160.preview&&{it:D160.preview.it,er:D160.preview.er},active:!!D160.gesture?.active,paused:PAUSE,hold:DECO2.hold}))}
async function scr(pg,wx,wy){return pg.evaluate(([x,y])=>{const r=cv.getBoundingClientRect(),d=devicePixelRatio||1;return [(x*T-camX)*SC/d+r.left,((y+ROOM2.rowsAbovePlan)*T-camY)*SC/d+r.top]},[wx,wy])}
async function points(pg,touch,condition,index){return pg.evaluate(({touch,condition,index})=>{
 const ix=index??M.layout2.findIndex(a=>a[0]==='plant'),base=M.layout2[ix],a=D164.rotation?.ref===base?D164.rotation.it:base,v=f2View(a[0],a[1]),r=cv.getBoundingClientRect(),d=devicePixelRatio||1;
 const xy=(x,y,lift)=>[(x*T-camX)*SC/d+r.left,((y+ROOM2.rowsAbovePlan)*T-camY)*SC/d+r.top+(lift?54:0)];
 const visible=p=>p[0]>6&&p[1]>6&&p[0]<innerWidth-6&&p[1]<innerHeight-6&&document.elementFromPoint(...p)===cv;
 let from=null;for(const oy of [v[7]/2,.2,-.4,-.8]){const p=xy(a[2]+v[6]/2,a[3]+oy,false);if(visible(p)&&deco2Hit(a[2]+v[6]/2,a[3]+oy)===ix){from={p,ox:v[6]/2,oy};break}}if(!from)return {error:'source not visible',a};
 for(let y=0;y<M.r2.grid.length;y+=.5)for(let x=0;x<M.w;x+=.5){const it=[a[0],a[1],x,y],p=xy(x+from.ox,y+from.oy,touch);if(!visible(p)||Math.hypot(x-a[2],y-a[3])<1)continue;
  const quick=f2Valid(it,base),er=quick||deco160Valid(it,base),px=P.x/T,py=P.y/T-ROOM2.rowsAbovePlan;
  const ok=condition==='valid'?!er:condition==='player'?er==='d2Block'&&x<=px&&px<x+v[6]&&y<=py&&py<y+v[7]:condition==='path'?quick===''&&er==='d2Block'&&Math.hypot(x-px,y-py)>3:er===condition;
  if(ok)return {index:ix,from:from.p,to:p,it,ox:from.ox,oy:from.oy};
 }return {error:'no visible '+condition,a,from,player:[P.x/T,P.y/T-ROOM2.rowsAbovePlan],probe:[6,6.5].map(y=>{const p=xy(P.x/T+from.ox,y+from.oy,touch);return {y,p,top:document.elementFromPoint(...p)?.outerHTML.slice(0,150),er:deco160Valid([a[0],a[1],P.x/T,y],a)}})};
 },{touch,condition,index})}
async function press(pg,sel,touch){const e=await pg.$(sel);assert(e,sel);await e.scrollIntoView();if(touch)await pg.tap(sel);else await pg.click(sel);await sleep(120)}
async function down(pg,cdp,p,touch){if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p[0],y:p[1],id:1}]});else{await pg.mouse.move(...p);await pg.mouse.down()}}
async function move(pg,cdp,a,b,touch){if(touch){for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a[0]+(b[0]-a[0])*i/10,y:a[1]+(b[1]-a[1])*i/10,id:1}]});await sleep(15)}}else await pg.mouse.move(...b,{steps:12});await sleep(180)}
async function up(pg,cdp,touch,cancel=false){if(touch)await cdp.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});else await pg.mouse.up();await sleep(150)}
async function colour(pg){return pg.evaluate(()=>{const p=D160.preview;if(!p)return {green:0,red:0};const a=p.it,v=f2View(a[0],a[1]),x=Math.max(0,Math.floor((a[2]*T-camX)*SC)),y=Math.max(0,Math.floor(((a[3]+ROOM2.rowsAbovePlan)*T-camY)*SC));
 const w=Math.min(cv.width-x,Math.ceil(v[6]*T*SC)),h=Math.min(cv.height-y,Math.ceil(v[7]*T*SC));if(w<=0||h<=0)return {green:0,red:0};const data=ctx.getImageData(x,y,w,h).data;let green=0,red=0;
 for(let i=0;i<data.length;i+=4){if(data[i+1]>data[i]+45&&data[i+1]>data[i+2]+25)green++;if(data[i]>data[i+1]+75&&data[i]>data[i+2]+65)red++}return {green,red};})}

(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXE,args:['--no-sandbox']}),results={};let pg;
try{for(const [tag,width,height,touch] of [['pc',1366,768,false],['phone',667,375,true]]){
 const bc=await browser.createBrowserContext();pg=await bc.newPage();const errors=[];pg.on('pageerror',e=>errors.push(e.message));await pg.setViewport({width,height,isMobile:touch,hasTouch:touch,deviceScaleFactor:touch?2:1});const cdp=await pg.target().createCDPSession();
 await pg.goto('http://localhost:'+(process.env.PORT||8775)+'/?gm',{waitUntil:'load'});await pg.waitForFunction(()=>!$('load')&&ROOM2,{timeout:40000});await pg.evaluate(()=>{gmMakeSlot();S=Store.all().slots[Store.all().cur];S.gmInit=1;S.seen={intro:1};S.snd=S.mus=false;startGame();document.querySelectorAll('#cr,#title,#picker').forEach(e=>e.classList.add('hide'));DLG=null;$('dlg').classList.add('hide');closeModal();goMap('room');P.x=11*T;P.y=8.5*T;P.path=null;fpsChecks=6;});await sleep(650);await press(pg,'#bDeco',touch);
 const ix=await pg.evaluate(()=>{const i=M.layout2.findIndex(a=>a[0]==='bed'),a=M.layout2[i];for(let y=4;y<10;y+=.5)for(let x=7;x<14;x+=.5){const it=[a[0],0,x,y],v=f2View(a[0],0),w=f2View(a[0],1),rot=[a[0],1,f2Snap(x+v[6]/2-w[6]/2),f2Snap(y+v[7]/2-w[7]/2)];if(deco160Valid(it,a)||deco160Valid(rot,a))continue;if(f2Apply(lay=>{lay[i][1]=0;lay[i][2]=x;lay[i][3]=y})){DECO2.sel=i;deco2UI();return i}}throw Error('bed fixture')});
 const initial=await state(pg);await press(pg,'#deco164 [data-a="turn"]',touch);const angle=await pg.evaluate(()=>D164.rotation.it[1]);assert.equal(angle,1);
 let p=await points(pg,touch,'valid',ix);assert(!p.error,JSON.stringify(p));await down(pg,cdp,p.from,touch);assert.equal(await pg.evaluate(()=>D164.rotation?.it[1]),angle,'grabbing the rotated bed must retain its pending angle');if(touch)await pg.waitForFunction(()=>D160.gesture?.active,{timeout:3000});await move(pg,cdp,p.from,p.to,touch);assert.equal((await state(pg)).preview.it[1],angle);assert.equal((await state(pg)).saved,initial.saved);await up(pg,cdp,touch);
 assert.equal(await pg.evaluate(()=>D164.rotation.it[1]),angle);assert.deepEqual(await pg.evaluate(()=>D164.rotation.it),p.it);assert.equal((await state(pg)).layout,initial.layout);assert.equal((await state(pg)).saved,initial.saved,'release waits for explicit confirmation of position and angle');
 const moved=await pg.evaluate(()=>D164.rotation.it.slice());await press(pg,'#deco164 [data-a="turn"]',touch);const again=await pg.evaluate(()=>D164.rotation.it.slice());assert.equal(again[1],2);const centers=await pg.evaluate(([a,b])=>{const av=f2View(a[0],a[1]),bv=f2View(b[0],b[1]);return [[a[2]+av[6]/2,a[3]+av[7]/2],[b[2]+bv[6]/2,b[3]+bv[7]/2]]},[moved,again]);assert(Math.hypot(centers[0][0]-centers[1][0],centers[0][1]-centers[1][1])<.36,'turn after move keeps moved centre');
 // Return to the valid quarter-turn, then exercise an invalid drop and a cancelled gesture.
 for(let n=0;n<3;n++)await press(pg,'#deco164 [data-a="turn"]',touch);const draft=await pg.evaluate(()=>D164.rotation.it.slice());assert.equal(draft[1],angle);
 p=await points(pg,touch,'valid',ix);assert(!p.error,JSON.stringify(p));await down(pg,cdp,p.from,touch);if(touch)await pg.waitForFunction(()=>D160.gesture?.active,{timeout:3000});else await pg.mouse.move(p.from[0]+7,p.from[1]);const bad=await points(pg,touch,'d2Wall',ix);assert(!bad.error,JSON.stringify(bad));await move(pg,cdp,p.from,bad.to,touch);assert((await state(pg)).preview.er);await up(pg,cdp,touch);assert.deepEqual(await pg.evaluate(()=>D164.rotation.it),draft);assert.equal((await state(pg)).saved,initial.saved);
 if(touch){p=await points(pg,touch,'valid',ix);await down(pg,cdp,p.from,true);await pg.waitForFunction(()=>D160.gesture?.active,{timeout:3000});await move(pg,cdp,p.from,p.to,true);await up(pg,cdp,true,true);assert.deepEqual(await pg.evaluate(()=>D164.rotation.it),draft)}
 await pg.screenshot({path:path.join(out,tag+'-moved-angle.png')});await press(pg,'#confirm164',touch);assert.deepEqual(await pg.evaluate(i=>M.layout2[i],ix),draft);assert.equal((await state(pg)).layout,(await state(pg)).saved);assert.equal((await state(pg)).stock,initial.stock);
 const confirmed=await state(pg);await press(pg,'#deco164 [data-a="turn"]',touch);
 // The visible preview is painted above furniture, so even its overlapping region remains grabbable.
 const hitCheck=await pg.evaluate(()=>{const it=D164.rotation.it,v=f2View(it[0],it[1]),i=M.layout2.indexOf(D164.rotation.ref);let tested=0;for(let y=it[3]-v[5]/T+.1;y<it[3]-v[5]/T+v[3]/T;y+=.25)for(let x=it[2]-v[4]/T+.1;x<it[2]-v[4]/T+v[2]/T;x+=.25){if(deco2Hit(x,y)!==i)return false;tested++}return tested>10});assert(hitCheck,'whole visible pending sprite is grabbable above overlapping furniture');p=await points(pg,touch,'valid',ix);assert(!p.error,JSON.stringify(p));await down(pg,cdp,p.from,touch);if(touch)await pg.waitForFunction(()=>D160.gesture?.active,{timeout:3000});await move(pg,cdp,p.from,p.to,touch);await up(pg,cdp,touch);await press(pg,'#cancel164',touch);assert.equal((await state(pg)).layout,confirmed.layout);assert.equal((await state(pg)).saved,confirmed.saved);
 await press(pg,'#deco2 [data-a="done"]',touch);await pg.reload({waitUntil:'load'});await pg.waitForFunction(()=>!$('load'),{timeout:40000});assert.equal(await pg.evaluate(()=>JSON.stringify(HOME.get().room2)),confirmed.saved);assert.deepEqual(errors,[]);results[tag]={rotateThenDrag:true,turnKeepsMovedCentre:true,invalidDropKeepsAngle:true,confirmationSavesBoth:true,cancelRestoresBoth:true,reloaded:true,errors:0};await bc.close();
}console.log(JSON.stringify(results));console.log('errors 0');}catch(e){console.error(e);if(pg&&!pg.isClosed())await pg.screenshot({path:path.join(out,'failure.png')});process.exitCode=1}finally{await browser.close()}})();
